module.exports = [
    {
      "orgName": "Dodhia Synthetic Limited",
      "data": [
        {
          "deviceId": "DSL_SUKA_1",
          "data": {
            "cpu_count": 0,
            "gpu_count": 0,
            "panel_count": 0,
            "vision_count": 0,
            "ampere_count": 0,
            "air_pressure_count": 0,
            "device_running": "00:00:00",
            "sorting_running": "00:00:00",
            "cpu_time": "00:00:00",
            "gpu_time": "00:00:00",
            "ampere_time": "00:00:00",
            "air_pressure_time": "00:00:00",
            "panel_time": "00:00:00",
            "vision_time": "00:00:00",
            "motorAmpereThreshold": 5.999999999999999,
            "airPressureLowerValueThreshold": 4.1,
            "upperPanelThreshold": 50,
            "maxCPUTemperatureThreshold": 90,
            "maxGPUTemperatureThreshold": 90,
            "upperVisionPanelThreshold": 50,
            "cpu_count_sw": 0,
            "gpu_count_sw": 0,
            "panel_count_sw": 0,
            "pressure_low_count_sw": 15,
            "vision_count_sw": 0,
            "motor_ampere_count_sw": 0,
            "cpufreq": "0 (undefined)",
            "gpufreq": "0 (undefined)",
            "panelfreq": "0 (undefined)",
            "visionfreq": "0 (undefined)",
            "pressurefreq": "15 (undefined)",
            "motorfreq": "0 (undefined)"
          }
        },
        {
          "deviceId": "DSL_SUKA_2",
          "data": {
            "cpu_count": 0,
            "gpu_count": 0,
            "panel_count": 0,
            "vision_count": 0,
            "ampere_count": 0,
            "air_pressure_count": 0,
            "device_running": "00:00:00",
            "sorting_running": "00:00:00",
            "cpu_time": "00:00:00",
            "gpu_time": "00:00:00",
            "ampere_time": "00:00:00",
            "air_pressure_time": "00:00:00",
            "panel_time": "00:00:00",
            "vision_time": "00:00:00",
            "motorAmpereThreshold": 6,
            "airPressureLowerValueThreshold": 4.5,
            "upperPanelThreshold": 50,
            "maxCPUTemperatureThreshold": 90,
            "maxGPUTemperatureThreshold": 90,
            "upperVisionPanelThreshold": 55,
            "cpu_count_sw": 0,
            "gpu_count_sw": 0,
            "panel_count_sw": 0,
            "pressure_low_count_sw": 1,
            "vision_count_sw": 0,
            "motor_ampere_count_sw": 0,
            "cpufreq": "0 (undefined)",
            "gpufreq": "0 (undefined)",
            "panelfreq": "0 (undefined)",
            "visionfreq": "0 (undefined)",
            "pressurefreq": "1 (undefined)",
            "motorfreq": "0 (undefined)"
          }
        },
        {
          "deviceId": "dsl-su14-10031",
          "data": {
            "cpu_count": 0,
            "gpu_count": 0,
            "panel_count": 0,
            "vision_count": 0,
            "ampere_count": 3,
            "air_pressure_count": 0,
            "device_running": "22:51:23",
            "sorting_running": "10:38:20",
            "cpu_val": "80.00",
            "gpu_val": "67.00",
            "panel_val": "48.00",
            "vision_val": "35.00",
            "ampere_val": "8.19",
            "air_pressure_val": "4.53",
            "cpu_time": "00:00:00",
            "gpu_time": "00:00:00",
            "ampere_time": "00:00:00",
            "air_pressure_time": "00:00:00",
            "panel_time": "00:00:00",
            "vision_time": "00:00:00",
            "motorAmpereThreshold": 7.799999999999999,
            "airPressureLowerValueThreshold": 4,
            "upperPanelThreshold": 62,
            "maxCPUTemperatureThreshold": 92,
            "maxGPUTemperatureThreshold": 80,
            "upperVisionPanelThreshold": 60,
            "cpu_count_sw": 0,
            "gpu_count_sw": 0,
            "panel_count_sw": 0,
            "pressure_low_count_sw": 0,
            "vision_count_sw": 0,
            "motor_ampere_count_sw": 2,
            "cpufreq": "0 (80.00)",
            "gpufreq": "0 (67.00)",
            "panelfreq": "0 (48.00)",
            "visionfreq": "0 (35.00)",
            "pressurefreq": "0 (4.53)",
            "motorfreq": "2 (8.19)"
          }
        },
        {
          "deviceId": "dsl-su20-10030",
          "data": {
            "cpu_count": 0,
            "gpu_count": 0,
            "panel_count": 0,
            "vision_count": 0,
            "ampere_count": 18,
            "air_pressure_count": 2,
            "device_running": "22:49:55",
            "sorting_running": "07:36:15",
            "cpu_val": "81.00",
            "gpu_val": "71.00",
            "panel_val": "51.00",
            "vision_val": "43.00",
            "ampere_val": "9.84",
            "air_pressure_val": "3.04",
            "cpu_time": "00:00:00",
            "gpu_time": "00:00:00",
            "ampere_time": "00:00:04",
            "air_pressure_time": "00:00:00",
            "panel_time": "00:00:00",
            "vision_time": "00:00:00",
            "motorAmpereThreshold": 7.499999999999998,
            "airPressureLowerValueThreshold": 4,
            "upperPanelThreshold": 62,
            "maxCPUTemperatureThreshold": 90,
            "maxGPUTemperatureThreshold": 80,
            "upperVisionPanelThreshold": 60,
            "cpu_count_sw": 0,
            "gpu_count_sw": 0,
            "panel_count_sw": 0,
            "pressure_low_count_sw": 2,
            "vision_count_sw": 0,
            "motor_ampere_count_sw": 2,
            "cpufreq": "0 (81.00)",
            "gpufreq": "0 (71.00)",
            "panelfreq": "0 (51.00)",
            "visionfreq": "0 (43.00)",
            "pressurefreq": "2 (3.04)",
            "motorfreq": "2 (9.84)"
          }
        },
        {
          "deviceId": "dsl-su20-10029",
          "data": {
            "cpu_count": 0,
            "gpu_count": 0,
            "panel_count": 0,
            "vision_count": 0,
            "ampere_count": 0,
            "air_pressure_count": 40,
            "device_running": "22:52:48",
            "sorting_running": "07:38:41",
            "cpu_val": "65.00",
            "gpu_val": "63.00",
            "panel_val": "39.00",
            "vision_val": "40.00",
            "ampere_val": "7.28",
            "air_pressure_val": "3.72",
            "cpu_time": "00:00:00",
            "gpu_time": "00:00:00",
            "ampere_time": "00:00:00",
            "air_pressure_time": "00:00:10",
            "panel_time": "00:00:00",
            "vision_time": "00:00:00",
            "motorAmpereThreshold": 7.499999999999998,
            "airPressureLowerValueThreshold": 4,
            "upperPanelThreshold": 62,
            "maxCPUTemperatureThreshold": 92,
            "maxGPUTemperatureThreshold": 80,
            "upperVisionPanelThreshold": 60,
            "cpu_count_sw": 0,
            "gpu_count_sw": 0,
            "panel_count_sw": 0,
            "pressure_low_count_sw": 40,
            "vision_count_sw": 0,
            "motor_ampere_count_sw": 0,
            "cpufreq": "0 (65.00)",
            "gpufreq": "0 (63.00)",
            "panelfreq": "0 (39.00)",
            "visionfreq": "0 (40.00)",
            "pressurefreq": "40 (3.72)",
            "motorfreq": "0 (7.28)"
          }
        },
        {
          "deviceId": "dsl-su20-10028",
          "data": {
            "cpu_count": 0,
            "gpu_count": 0,
            "panel_count": 0,
            "vision_count": 0,
            "ampere_count": 0,
            "air_pressure_count": 0,
            "device_running": "22:50:11",
            "sorting_running": "10:04:36",
            "cpu_val": "66.00",
            "gpu_val": "66.00",
            "panel_val": "36.00",
            "vision_val": "43.00",
            "ampere_val": "7.35",
            "air_pressure_val": "4.74",
            "cpu_time": "00:00:00",
            "gpu_time": "00:00:00",
            "ampere_time": "00:00:00",
            "air_pressure_time": "00:00:00",
            "panel_time": "00:00:00",
            "vision_time": "00:00:00",
            "motorAmpereThreshold": 7.499999999999995,
            "airPressureLowerValueThreshold": 4,
            "upperPanelThreshold": 62,
            "maxCPUTemperatureThreshold": 90,
            "maxGPUTemperatureThreshold": 80,
            "upperVisionPanelThreshold": 60,
            "cpu_count_sw": 0,
            "gpu_count_sw": 0,
            "panel_count_sw": 0,
            "pressure_low_count_sw": 0,
            "vision_count_sw": 0,
            "motor_ampere_count_sw": 0,
            "cpufreq": "0 (66.00)",
            "gpufreq": "0 (66.00)",
            "panelfreq": "0 (36.00)",
            "visionfreq": "0 (43.00)",
            "pressurefreq": "0 (4.74)",
            "motorfreq": "0 (7.35)"
          }
        },
        {
          "deviceId": "dsl-su20-10027",
          "data": {
            "cpu_count": 0,
            "gpu_count": 0,
            "panel_count": 0,
            "vision_count": 0,
            "ampere_count": 6,
            "air_pressure_count": 1,
            "device_running": "22:50:22",
            "sorting_running": "10:04:17",
            "cpu_val": "80.00",
            "gpu_val": "72.00",
            "panel_val": "49.00",
            "vision_val": "38.00",
            "ampere_val": "7.54",
            "air_pressure_val": "2.66",
            "cpu_time": "00:00:00",
            "gpu_time": "00:00:00",
            "ampere_time": "00:00:01",
            "air_pressure_time": "00:00:00",
            "panel_time": "00:00:00",
            "vision_time": "00:00:00",
            "motorAmpereThreshold": 7.499999999999995,
            "airPressureLowerValueThreshold": 4,
            "upperPanelThreshold": 62,
            "maxCPUTemperatureThreshold": 90,
            "maxGPUTemperatureThreshold": 80,
            "upperVisionPanelThreshold": 60,
            "cpu_count_sw": 0,
            "gpu_count_sw": 0,
            "panel_count_sw": 0,
            "pressure_low_count_sw": 1,
            "vision_count_sw": 0,
            "motor_ampere_count_sw": 0,
            "cpufreq": "0 (80.00)",
            "gpufreq": "0 (72.00)",
            "panelfreq": "0 (49.00)",
            "visionfreq": "0 (38.00)",
            "pressurefreq": "1 (2.66)",
            "motorfreq": "0 (7.54)"
          }
        }
      ]
    },
    {
      "orgName": "Pashupati Polyplex Pvt Ltd",
      "data": [
        {
          "deviceId": "PPP_SUKA_1",
          "data": {
            "cpu_count": 0,
            "gpu_count": 0,
            "panel_count": 0,
            "vision_count": 0,
            "ampere_count": 0,
            "air_pressure_count": 0,
            "device_running": "00:00:00",
            "sorting_running": "00:00:00",
            "cpu_time": "00:00:00",
            "gpu_time": "00:00:00",
            "ampere_time": "00:00:00",
            "air_pressure_time": "00:00:00",
            "panel_time": "00:00:00",
            "vision_time": "00:00:00",
            "motorAmpereThreshold": 5.999999999999999,
            "airPressureLowerValueThreshold": 4,
            "upperPanelThreshold": 50,
            "maxCPUTemperatureThreshold": 95,
            "maxGPUTemperatureThreshold": 95,
            "upperVisionPanelThreshold": 50,
            "cpu_count_sw": 0,
            "gpu_count_sw": 0,
            "panel_count_sw": 0,
            "pressure_low_count_sw": 0,
            "vision_count_sw": 0,
            "motor_ampere_count_sw": 0,
            "cpufreq": "0 (undefined)",
            "gpufreq": "0 (undefined)",
            "panelfreq": "0 (undefined)",
            "visionfreq": "0 (undefined)",
            "pressurefreq": "0 (undefined)",
            "motorfreq": "0 (undefined)"
          }
        },
        {
          "deviceId": "PPP_SUKA_2",
          "data": {
            "cpu_count": 0,
            "gpu_count": 0,
            "panel_count": 0,
            "vision_count": 0,
            "ampere_count": 0,
            "air_pressure_count": 0,
            "device_running": "00:00:00",
            "sorting_running": "00:00:00",
            "cpu_time": "00:00:00",
            "gpu_time": "00:00:00",
            "ampere_time": "00:00:00",
            "air_pressure_time": "00:00:00",
            "panel_time": "00:00:00",
            "vision_time": "00:00:00",
            "motorAmpereThreshold": 5.999999999999999,
            "airPressureLowerValueThreshold": 4,
            "upperPanelThreshold": 50,
            "maxCPUTemperatureThreshold": 90,
            "maxGPUTemperatureThreshold": 90,
            "upperVisionPanelThreshold": 50,
            "cpu_count_sw": 0,
            "gpu_count_sw": 0,
            "panel_count_sw": 0,
            "pressure_low_count_sw": 0,
            "vision_count_sw": 0,
            "motor_ampere_count_sw": 0,
            "cpufreq": "0 (undefined)",
            "gpufreq": "0 (undefined)",
            "panelfreq": "0 (undefined)",
            "visionfreq": "0 (undefined)",
            "pressurefreq": "0 (undefined)",
            "motorfreq": "0 (undefined)"
          }
        },
        {
          "deviceId": "PPP_SUKA_3",
          "data": {
            "cpu_count": 0,
            "gpu_count": 0,
            "panel_count": 0,
            "vision_count": 0,
            "ampere_count": 0,
            "air_pressure_count": 0,
            "device_running": "00:00:00",
            "sorting_running": "00:00:00",
            "cpu_time": "00:00:00",
            "gpu_time": "00:00:00",
            "ampere_time": "00:00:00",
            "air_pressure_time": "00:00:00",
            "panel_time": "00:00:00",
            "vision_time": "00:00:00",
            "motorAmpereThreshold": 5.999999999999999,
            "airPressureLowerValueThreshold": 4,
            "upperPanelThreshold": 50,
            "maxCPUTemperatureThreshold": 90,
            "maxGPUTemperatureThreshold": 90,
            "upperVisionPanelThreshold": 50,
            "cpu_count_sw": 0,
            "gpu_count_sw": 0,
            "panel_count_sw": 0,
            "pressure_low_count_sw": 0,
            "vision_count_sw": 0,
            "motor_ampere_count_sw": 0,
            "cpufreq": "0 (undefined)",
            "gpufreq": "0 (undefined)",
            "panelfreq": "0 (undefined)",
            "visionfreq": "0 (undefined)",
            "pressurefreq": "0 (undefined)",
            "motorfreq": "0 (undefined)"
          }
        }
      ]
    },
    {
      "orgName": "Ishitva Robotic Systems",
      "data": [
        {
          "deviceId": "CHANGODAR_2_MTR",
          "data": {
            "cpu_count": 0,
            "gpu_count": 0,
            "panel_count": 0,
            "vision_count": 0,
            "ampere_count": 0,
            "air_pressure_count": 0,
            "device_running": "00:00:00",
            "sorting_running": "00:00:00",
            "cpu_time": "00:00:00",
            "gpu_time": "00:00:00",
            "ampere_time": "00:00:00",
            "air_pressure_time": "00:00:00",
            "panel_time": "00:00:00",
            "vision_time": "00:00:00",
            "motorAmpereThreshold": 7.800000000000001,
            "airPressureLowerValueThreshold": 4.5,
            "upperPanelThreshold": 50,
            "maxCPUTemperatureThreshold": 100,
            "maxGPUTemperatureThreshold": 90,
            "upperVisionPanelThreshold": 55,
            "cpu_count_sw": 0,
            "gpu_count_sw": 0,
            "panel_count_sw": 0,
            "pressure_low_count_sw": 0,
            "vision_count_sw": 0,
            "motor_ampere_count_sw": 0,
            "cpufreq": "0 (undefined)",
            "gpufreq": "0 (undefined)",
            "panelfreq": "0 (undefined)",
            "visionfreq": "0 (undefined)",
            "pressurefreq": "0 (undefined)",
            "motorfreq": "0 (undefined)"
          }
        },
        {
          "deviceId": "PLAST-VISION",
          "data": {
            "cpu_count": 0,
            "gpu_count": 0,
            "panel_count": 0,
            "vision_count": 0,
            "ampere_count": 0,
            "air_pressure_count": 0,
            "device_running": "00:00:00",
            "sorting_running": "00:00:00",
            "cpu_time": "00:00:00",
            "gpu_time": "00:00:00",
            "ampere_time": "00:00:00",
            "air_pressure_time": "00:00:00",
            "panel_time": "00:00:00",
            "vision_time": "00:00:00",
            "motorAmpereThreshold": 6,
            "airPressureLowerValueThreshold": 4.5,
            "upperPanelThreshold": 50,
            "maxCPUTemperatureThreshold": 95,
            "maxGPUTemperatureThreshold": 90,
            "upperVisionPanelThreshold": 55,
            "cpu_count_sw": 0,
            "gpu_count_sw": 0,
            "panel_count_sw": 0,
            "pressure_low_count_sw": 0,
            "vision_count_sw": 0,
            "motor_ampere_count_sw": 0,
            "cpufreq": "0 (undefined)",
            "gpufreq": "0 (undefined)",
            "panelfreq": "0 (undefined)",
            "visionfreq": "0 (undefined)",
            "pressurefreq": "0 (undefined)",
            "motorfreq": "0 (undefined)"
          }
        },
        {
          "deviceId": "SRICHAKRA_SUKA_1",
          "data": {
            "cpu_count": 0,
            "gpu_count": 0,
            "panel_count": 0,
            "vision_count": 0,
            "ampere_count": 0,
            "air_pressure_count": 0,
            "device_running": "00:00:00",
            "sorting_running": "00:00:00",
            "cpu_time": "00:00:00",
            "gpu_time": "00:00:00",
            "ampere_time": "00:00:00",
            "air_pressure_time": "00:00:00",
            "panel_time": "00:00:00",
            "vision_time": "00:00:00",
            "motorAmpereThreshold": 7.999999999999993,
            "airPressureLowerValueThreshold": 4.5,
            "upperPanelThreshold": 62,
            "maxCPUTemperatureThreshold": 90,
            "maxGPUTemperatureThreshold": 80,
            "upperVisionPanelThreshold": 55,
            "cpu_count_sw": 0,
            "gpu_count_sw": 0,
            "panel_count_sw": 0,
            "pressure_low_count_sw": 0,
            "vision_count_sw": 0,
            "motor_ampere_count_sw": 0,
            "cpufreq": "0 (undefined)",
            "gpufreq": "0 (undefined)",
            "panelfreq": "0 (undefined)",
            "visionfreq": "0 (undefined)",
            "pressurefreq": "0 (undefined)",
            "motorfreq": "0 (undefined)"
          }
        },
        {
          "deviceId": "test",
          "data": {
            "cpu_count": 0,
            "gpu_count": 0,
            "panel_count": 0,
            "vision_count": 0,
            "ampere_count": 0,
            "air_pressure_count": 609,
            "device_running": "00:02:40",
            "sorting_running": "00:00:00",
            "cpu_val": "84.00",
            "gpu_val": "51.00",
            "panel_val": "30.00",
            "vision_val": "30.00",
            "ampere_val": "0.00",
            "air_pressure_val": "0.00",
            "cpu_time": "00:00:00",
            "gpu_time": "00:00:00",
            "ampere_time": "00:00:00",
            "air_pressure_time": "00:02:32",
            "panel_time": "00:00:00",
            "vision_time": "00:00:00",
            "motorAmpereThreshold": 6,
            "airPressureLowerValueThreshold": 4.5,
            "upperPanelThreshold": 62,
            "maxCPUTemperatureThreshold": 90,
            "maxGPUTemperatureThreshold": 80,
            "upperVisionPanelThreshold": 55,
            "cpu_count_sw": 0,
            "gpu_count_sw": 0,
            "panel_count_sw": 0,
            "pressure_low_count_sw": 1,
            "vision_count_sw": 0,
            "motor_ampere_count_sw": 0,
            "cpufreq": "0 (84.00)",
            "gpufreq": "0 (51.00)",
            "panelfreq": "0 (30.00)",
            "visionfreq": "0 (30.00)",
            "pressurefreq": "1 (0.00)",
            "motorfreq": "0 (0.00)"
          }
        },
        {
          "deviceId": "PLASTVISION_1.4M",
          "data": {
            "cpu_count": 0,
            "gpu_count": 0,
            "panel_count": 0,
            "vision_count": 0,
            "ampere_count": 0,
            "air_pressure_count": 0,
            "device_running": "00:00:00",
            "sorting_running": "00:00:00",
            "cpu_time": "00:00:00",
            "gpu_time": "00:00:00",
            "ampere_time": "00:00:00",
            "air_pressure_time": "00:00:00",
            "panel_time": "00:00:00",
            "vision_time": "00:00:00",
            "motorAmpereThreshold": 7.000000000000002,
            "airPressureLowerValueThreshold": 4.2,
            "upperPanelThreshold": 60,
            "maxCPUTemperatureThreshold": 100,
            "maxGPUTemperatureThreshold": 90,
            "upperVisionPanelThreshold": 65,
            "cpu_count_sw": 0,
            "gpu_count_sw": 0,
            "panel_count_sw": 0,
            "pressure_low_count_sw": 0,
            "vision_count_sw": 0,
            "motor_ampere_count_sw": 0,
            "cpufreq": "0 (undefined)",
            "gpufreq": "0 (undefined)",
            "panelfreq": "0 (undefined)",
            "visionfreq": "0 (undefined)",
            "pressurefreq": "0 (undefined)",
            "motorfreq": "0 (undefined)"
          }
        },
        {
          "deviceId": "black_sanjivani",
          "data": {
            "cpu_count": 0,
            "gpu_count": 0,
            "panel_count": 0,
            "vision_count": 0,
            "ampere_count": 0,
            "air_pressure_count": 0,
            "device_running": "00:00:00",
            "sorting_running": "00:00:00",
            "cpu_time": "00:00:00",
            "gpu_time": "00:00:00",
            "ampere_time": "00:00:00",
            "air_pressure_time": "00:00:00",
            "panel_time": "00:00:00",
            "vision_time": "00:00:00",
            "motorAmpereThreshold": 7.5,
            "airPressureLowerValueThreshold": 4.2,
            "upperPanelThreshold": 62,
            "maxCPUTemperatureThreshold": 80,
            "maxGPUTemperatureThreshold": 80,
            "upperVisionPanelThreshold": 55,
            "cpu_count_sw": 0,
            "gpu_count_sw": 0,
            "panel_count_sw": 0,
            "pressure_low_count_sw": 0,
            "vision_count_sw": 0,
            "motor_ampere_count_sw": 0,
            "cpufreq": "0 (undefined)",
            "gpufreq": "0 (undefined)",
            "panelfreq": "0 (undefined)",
            "visionfreq": "0 (undefined)",
            "pressurefreq": "0 (undefined)",
            "motorfreq": "0 (undefined)"
          }
        },
        {
          "deviceId": "ML_TEAM",
          "data": {
            "cpu_count": 0,
            "gpu_count": 0,
            "panel_count": 0,
            "vision_count": 0,
            "ampere_count": 0,
            "air_pressure_count": 0,
            "device_running": "00:00:37",
            "sorting_running": "00:00:00",
            "cpu_val": "69.00",
            "gpu_val": "60.00",
            "panel_val": "30.00",
            "vision_val": "30.00",
            "ampere_val": "0.00",
            "air_pressure_val": "5.60",
            "cpu_time": "00:00:00",
            "gpu_time": "00:00:00",
            "ampere_time": "00:00:00",
            "air_pressure_time": "00:00:00",
            "panel_time": "00:00:00",
            "vision_time": "00:00:00",
            "motorAmpereThreshold": 6,
            "airPressureLowerValueThreshold": 4.5,
            "upperPanelThreshold": 50,
            "maxCPUTemperatureThreshold": 90,
            "maxGPUTemperatureThreshold": 90,
            "upperVisionPanelThreshold": 55,
            "cpu_count_sw": 0,
            "gpu_count_sw": 0,
            "panel_count_sw": 0,
            "pressure_low_count_sw": 0,
            "vision_count_sw": 0,
            "motor_ampere_count_sw": 0,
            "cpufreq": "0 (69.00)",
            "gpufreq": "0 (60.00)",
            "panelfreq": "0 (30.00)",
            "visionfreq": "0 (30.00)",
            "pressurefreq": "0 (5.60)",
            "motorfreq": "0 (0.00)"
          }
        }
      ]
    },
    {
      "orgName": "Srichakra Polyplast India",
      "data": [
        {
          "deviceId": "SRICHAKRA_SUKA_1_1",
          "data": {
            "cpu_count": 0,
            "gpu_count": 0,
            "panel_count": 0,
            "vision_count": 0,
            "ampere_count": 243955,
            "air_pressure_count": 5143,
            "device_running": "23:37:05",
            "sorting_running": "23:36:56",
            "cpu_val": "91.00",
            "gpu_val": "67.00",
            "panel_val": "0.00",
            "vision_val": "0.00",
            "ampere_val": "10.40",
            "air_pressure_val": "3.64",
            "cpu_time": "00:00:00",
            "gpu_time": "00:00:00",
            "ampere_time": "16:56:28",
            "air_pressure_time": "00:21:25",
            "panel_time": "00:00:00",
            "vision_time": "00:00:00",
            "motorAmpereThreshold": 6,
            "airPressureLowerValueThreshold": 4.5,
            "upperPanelThreshold": 50,
            "maxCPUTemperatureThreshold": 100,
            "maxGPUTemperatureThreshold": 90,
            "upperVisionPanelThreshold": 55,
            "cpu_count_sw": 0,
            "gpu_count_sw": 0,
            "panel_count_sw": 0,
            "pressure_low_count_sw": 3731,
            "vision_count_sw": 0,
            "motor_ampere_count_sw": 0,
            "cpufreq": "0 (91.00)",
            "gpufreq": "0 (67.00)",
            "panelfreq": "0 (0.00)",
            "visionfreq": "0 (0.00)",
            "pressurefreq": "3731 (3.64)",
            "motorfreq": "0 (10.40)"
          }
        },
        {
          "deviceId": "SUKA-AI-V3-1.4-10050",
          "data": {
            "cpu_count": 0,
            "gpu_count": 944,
            "panel_count": 0,
            "vision_count": 0,
            "ampere_count": 8,
            "air_pressure_count": 1,
            "device_running": "22:32:17",
            "sorting_running": "22:31:40",
            "cpu_val": "83.00",
            "gpu_val": "82.00",
            "panel_val": "39.00",
            "vision_val": "35.00",
            "ampere_val": "6.89",
            "air_pressure_val": "3.98",
            "cpu_time": "00:00:00",
            "gpu_time": "00:03:56",
            "ampere_time": "00:00:02",
            "air_pressure_time": "00:00:00",
            "panel_time": "00:00:00",
            "vision_time": "00:00:00",
            "motorAmpereThreshold": 5.5,
            "airPressureLowerValueThreshold": 4.2,
            "upperPanelThreshold": 62,
            "maxCPUTemperatureThreshold": 85,
            "maxGPUTemperatureThreshold": 80,
            "upperVisionPanelThreshold": 55,
            "cpu_count_sw": 0,
            "gpu_count_sw": 7,
            "panel_count_sw": 0,
            "pressure_low_count_sw": 1,
            "vision_count_sw": 0,
            "motor_ampere_count_sw": 0,
            "cpufreq": "0 (83.00)",
            "gpufreq": "7 (82.00)",
            "panelfreq": "0 (39.00)",
            "visionfreq": "0 (35.00)",
            "pressurefreq": "1 (3.98)",
            "motorfreq": "0 (6.89)"
          }
        }
      ]
    },
    {
      "orgName": "Mk Plastics",
      "data": [
        {
          "deviceId": "MKP_SUKA_1",
          "data": {
            "cpu_count": 0,
            "gpu_count": 0,
            "panel_count": 0,
            "vision_count": 0,
            "ampere_count": 42,
            "air_pressure_count": 1,
            "device_running": "12:05:12",
            "sorting_running": "09:54:56",
            "cpu_val": "83.00",
            "gpu_val": "71.00",
            "ampere_val": "7.65",
            "air_pressure_val": "0.00",
            "cpu_time": "00:00:00",
            "gpu_time": "00:00:00",
            "ampere_time": "00:00:10",
            "air_pressure_time": "00:00:00",
            "panel_time": "00:00:00",
            "vision_time": "00:00:00",
            "motorAmpereThreshold": 6,
            "airPressureLowerValueThreshold": 4,
            "upperPanelThreshold": 50,
            "maxCPUTemperatureThreshold": 90,
            "maxGPUTemperatureThreshold": 90,
            "upperVisionPanelThreshold": 55,
            "cpu_count_sw": 0,
            "gpu_count_sw": 0,
            "panel_count_sw": 0,
            "pressure_low_count_sw": 1,
            "vision_count_sw": 0,
            "motor_ampere_count_sw": 0,
            "cpufreq": "0 (83.00)",
            "gpufreq": "0 (71.00)",
            "panelfreq": "0 (undefined)",
            "visionfreq": "0 (undefined)",
            "pressurefreq": "1 (0.00)",
            "motorfreq": "0 (7.65)"
          }
        }
      ]
    },
    {
      "orgName": "Nepra Resource Management",
      "data": [
        {
          "deviceId": "JNAS_1200",
          "data": {
            "cpu_count": 0,
            "gpu_count": 0,
            "panel_count": 0,
            "vision_count": 0,
            "ampere_count": 0,
            "air_pressure_count": 0,
            "device_running": "00:00:00",
            "sorting_running": "00:00:00",
            "cpu_time": "00:00:00",
            "gpu_time": "00:00:00",
            "ampere_time": "00:00:00",
            "air_pressure_time": "00:00:00",
            "panel_time": "00:00:00",
            "vision_time": "00:00:00",
            "motorAmpereThreshold": 0,
            "airPressureLowerValueThreshold": 0,
            "upperPanelThreshold": 0,
            "maxCPUTemperatureThreshold": 0,
            "maxGPUTemperatureThreshold": 0,
            "upperVisionPanelThreshold": 0,
            "cpu_count_sw": 0,
            "gpu_count_sw": 0,
            "panel_count_sw": 0,
            "pressure_low_count_sw": 0,
            "vision_count_sw": 0,
            "motor_ampere_count_sw": 0,
            "cpufreq": "0 (undefined)",
            "gpufreq": "0 (undefined)",
            "panelfreq": "0 (undefined)",
            "visionfreq": "0 (undefined)",
            "pressurefreq": "0 (undefined)",
            "motorfreq": "0 (undefined)"
          }
        },
        {
          "deviceId": "JNAS_1000",
          "data": {
            "cpu_count": 0,
            "gpu_count": 0,
            "panel_count": 0,
            "vision_count": 0,
            "ampere_count": 0,
            "air_pressure_count": 0,
            "device_running": "00:00:00",
            "sorting_running": "00:00:00",
            "cpu_time": "00:00:00",
            "gpu_time": "00:00:00",
            "ampere_time": "00:00:00",
            "air_pressure_time": "00:00:00",
            "panel_time": "00:00:00",
            "vision_time": "00:00:00",
            "motorAmpereThreshold": 0,
            "airPressureLowerValueThreshold": 0,
            "upperPanelThreshold": 0,
            "maxCPUTemperatureThreshold": 0,
            "maxGPUTemperatureThreshold": 0,
            "upperVisionPanelThreshold": 0,
            "cpu_count_sw": 0,
            "gpu_count_sw": 0,
            "panel_count_sw": 0,
            "pressure_low_count_sw": 0,
            "vision_count_sw": 0,
            "motor_ampere_count_sw": 0,
            "cpufreq": "0 (undefined)",
            "gpufreq": "0 (undefined)",
            "panelfreq": "0 (undefined)",
            "visionfreq": "0 (undefined)",
            "pressurefreq": "0 (undefined)",
            "motorfreq": "0 (undefined)"
          }
        },
        {
          "deviceId": "SANTEJ_800",
          "data": {
            "cpu_count": 0,
            "gpu_count": 0,
            "panel_count": 0,
            "vision_count": 0,
            "ampere_count": 0,
            "air_pressure_count": 0,
            "device_running": "00:00:00",
            "sorting_running": "00:00:00",
            "cpu_time": "00:00:00",
            "gpu_time": "00:00:00",
            "ampere_time": "00:00:00",
            "air_pressure_time": "00:00:00",
            "panel_time": "00:00:00",
            "vision_time": "00:00:00",
            "motorAmpereThreshold": 0,
            "airPressureLowerValueThreshold": 0,
            "upperPanelThreshold": 0,
            "maxCPUTemperatureThreshold": 0,
            "maxGPUTemperatureThreshold": 0,
            "upperVisionPanelThreshold": 0,
            "cpu_count_sw": 0,
            "gpu_count_sw": 0,
            "panel_count_sw": 0,
            "pressure_low_count_sw": 0,
            "vision_count_sw": 0,
            "motor_ampere_count_sw": 0,
            "cpufreq": "0 (undefined)",
            "gpufreq": "0 (undefined)",
            "panelfreq": "0 (undefined)",
            "visionfreq": "0 (undefined)",
            "pressurefreq": "0 (undefined)",
            "motorfreq": "0 (undefined)"
          }
        }
      ]
    },
    {
      "orgName": "Rpg",
      "data": [
        {
          "deviceId": "rpg-su20-10038",
          "data": {
            "cpu_count": 0,
            "gpu_count": 0,
            "panel_count": 0,
            "vision_count": 0,
            "ampere_count": 1152,
            "air_pressure_count": 1282,
            "device_running": "23:47:50",
            "sorting_running": "16:15:15",
            "cpu_val": "71.00",
            "gpu_val": "68.00",
            "panel_val": "38.00",
            "vision_val": "47.00",
            "ampere_val": "11.24",
            "air_pressure_val": "3.67",
            "cpu_time": "00:00:00",
            "gpu_time": "00:00:00",
            "ampere_time": "00:04:48",
            "air_pressure_time": "00:05:20",
            "panel_time": "00:00:00",
            "vision_time": "00:00:00",
            "motorAmpereThreshold": 6.699999999999999,
            "airPressureLowerValueThreshold": 4.5,
            "upperPanelThreshold": 62,
            "maxCPUTemperatureThreshold": 80,
            "maxGPUTemperatureThreshold": 80,
            "upperVisionPanelThreshold": 62,
            "cpu_count_sw": 0,
            "gpu_count_sw": 0,
            "panel_count_sw": 0,
            "pressure_low_count_sw": 945,
            "vision_count_sw": 0,
            "motor_ampere_count_sw": 0,
            "cpufreq": "0 (71.00)",
            "gpufreq": "0 (68.00)",
            "panelfreq": "0 (38.00)",
            "visionfreq": "0 (47.00)",
            "pressurefreq": "945 (3.67)",
            "motorfreq": "0 (11.24)"
          }
        },
        {
          "deviceId": "RPG-SU20-10047",
          "data": {
            "cpu_count": 0,
            "gpu_count": 0,
            "panel_count": 0,
            "vision_count": 0,
            "ampere_count": 11,
            "air_pressure_count": 2510,
            "device_running": "23:48:05",
            "sorting_running": "18:09:56",
            "cpu_val": "76.00",
            "gpu_val": "73.00",
            "panel_val": "42.00",
            "vision_val": "40.00",
            "ampere_val": "9.13",
            "air_pressure_val": "3.18",
            "cpu_time": "00:00:00",
            "gpu_time": "00:00:00",
            "ampere_time": "00:00:02",
            "air_pressure_time": "00:10:27",
            "panel_time": "00:00:00",
            "vision_time": "00:00:00",
            "motorAmpereThreshold": 7.099999999999999,
            "airPressureLowerValueThreshold": 4.5,
            "upperPanelThreshold": 62,
            "maxCPUTemperatureThreshold": 80,
            "maxGPUTemperatureThreshold": 80,
            "upperVisionPanelThreshold": 55,
            "cpu_count_sw": 0,
            "gpu_count_sw": 0,
            "panel_count_sw": 0,
            "pressure_low_count_sw": 1585,
            "vision_count_sw": 0,
            "motor_ampere_count_sw": 0,
            "cpufreq": "0 (76.00)",
            "gpufreq": "0 (73.00)",
            "panelfreq": "0 (42.00)",
            "visionfreq": "0 (40.00)",
            "pressurefreq": "1585 (3.18)",
            "motorfreq": "0 (9.13)"
          }
        }
      ]
    },
    {
      "orgName": "Sulochana Cotton Mills Pvt Ltd",
      "data": [
        {
          "deviceId": "SCM-SU14-10039",
          "data": {
            "cpu_count": 0,
            "gpu_count": 0,
            "panel_count": 0,
            "vision_count": 0,
            "ampere_count": 0,
            "air_pressure_count": 24843,
            "device_running": "22:11:38",
            "sorting_running": "19:27:52",
            "cpu_val": "76.00",
            "gpu_val": "70.00",
            "panel_val": "38.00",
            "vision_val": "38.00",
            "ampere_val": "5.00",
            "air_pressure_val": "0.02",
            "cpu_time": "00:00:00",
            "gpu_time": "00:00:00",
            "ampere_time": "00:00:00",
            "air_pressure_time": "01:43:30",
            "panel_time": "00:00:00",
            "vision_time": "00:00:00",
            "motorAmpereThreshold": 5.200000000000003,
            "airPressureLowerValueThreshold": 4.2,
            "upperPanelThreshold": 62,
            "maxCPUTemperatureThreshold": 85,
            "maxGPUTemperatureThreshold": 80,
            "upperVisionPanelThreshold": 60,
            "cpu_count_sw": 0,
            "gpu_count_sw": 0,
            "panel_count_sw": 0,
            "pressure_low_count_sw": 19,
            "vision_count_sw": 0,
            "motor_ampere_count_sw": 0,
            "cpufreq": "0 (76.00)",
            "gpufreq": "0 (70.00)",
            "panelfreq": "0 (38.00)",
            "visionfreq": "0 (38.00)",
            "pressurefreq": "19 (0.02)",
            "motorfreq": "0 (5.00)"
          }
        }
      ]
    },
    {
      "orgName": "Alliance",
      "data": [
        {
          "deviceId": "SUK-AL-V3-2.0-10045",
          "data": {
            "cpu_count": 33,
            "gpu_count": 0,
            "panel_count": 0,
            "vision_count": 0,
            "ampere_count": 350,
            "air_pressure_count": 0,
            "device_running": "23:38:43",
            "sorting_running": "21:01:53",
            "cpu_val": "88.00",
            "gpu_val": "78.00",
            "panel_val": "48.00",
            "vision_val": "42.00",
            "ampere_val": "14.29",
            "air_pressure_val": "4.49",
            "cpu_time": "00:00:08",
            "gpu_time": "00:00:00",
            "ampere_time": "00:01:27",
            "air_pressure_time": "00:00:00",
            "panel_time": "00:00:00",
            "vision_time": "00:00:00",
            "motorAmpereThreshold": 7.500000000000001,
            "airPressureLowerValueThreshold": 4,
            "upperPanelThreshold": 62,
            "maxCPUTemperatureThreshold": 87,
            "maxGPUTemperatureThreshold": 80,
            "upperVisionPanelThreshold": 60,
            "cpu_count_sw": 0,
            "gpu_count_sw": 0,
            "panel_count_sw": 0,
            "pressure_low_count_sw": 0,
            "vision_count_sw": 0,
            "motor_ampere_count_sw": 21,
            "cpufreq": "0 (88.00)",
            "gpufreq": "0 (78.00)",
            "panelfreq": "0 (48.00)",
            "visionfreq": "0 (42.00)",
            "pressurefreq": "0 (4.49)",
            "motorfreq": "21 (14.29)"
          }
        },
        {
          "deviceId": "SUK-AL-V3-2.0-10042",
          "data": {
            "cpu_count": 173,
            "gpu_count": 3656,
            "panel_count": 0,
            "vision_count": 0,
            "ampere_count": 8,
            "air_pressure_count": 0,
            "device_running": "23:38:48",
            "sorting_running": "20:54:07",
            "cpu_val": "88.00",
            "gpu_val": "82.00",
            "panel_val": "50.00",
            "vision_val": "42.00",
            "ampere_val": "9.11",
            "air_pressure_val": "4.88",
            "cpu_time": "00:00:43",
            "gpu_time": "00:15:14",
            "ampere_time": "00:00:02",
            "air_pressure_time": "00:00:00",
            "panel_time": "00:00:00",
            "vision_time": "00:00:00",
            "motorAmpereThreshold": 7.500000000000002,
            "airPressureLowerValueThreshold": 4,
            "upperPanelThreshold": 62,
            "maxCPUTemperatureThreshold": 87,
            "maxGPUTemperatureThreshold": 80,
            "upperVisionPanelThreshold": 60,
            "cpu_count_sw": 0,
            "gpu_count_sw": 35,
            "panel_count_sw": 0,
            "pressure_low_count_sw": 0,
            "vision_count_sw": 0,
            "motor_ampere_count_sw": 0,
            "cpufreq": "0 (88.00)",
            "gpufreq": "35 (82.00)",
            "panelfreq": "0 (50.00)",
            "visionfreq": "0 (42.00)",
            "pressurefreq": "0 (4.88)",
            "motorfreq": "0 (9.11)"
          }
        },
        {
          "deviceId": "SUK-AL-V3-2.0-10043",
          "data": {
            "cpu_count": 0,
            "gpu_count": 0,
            "panel_count": 0,
            "vision_count": 0,
            "ampere_count": 58,
            "air_pressure_count": 0,
            "device_running": "23:39:16",
            "sorting_running": "20:52:29",
            "cpu_val": "86.00",
            "gpu_val": "77.00",
            "panel_val": "50.00",
            "vision_val": "46.00",
            "ampere_val": "12.10",
            "air_pressure_val": "4.41",
            "cpu_time": "00:00:00",
            "gpu_time": "00:00:00",
            "ampere_time": "00:00:14",
            "air_pressure_time": "00:00:00",
            "panel_time": "00:00:00",
            "vision_time": "00:00:00",
            "motorAmpereThreshold": 7.100000000000001,
            "airPressureLowerValueThreshold": 4,
            "upperPanelThreshold": 62,
            "maxCPUTemperatureThreshold": 87,
            "maxGPUTemperatureThreshold": 80,
            "upperVisionPanelThreshold": 62,
            "cpu_count_sw": 0,
            "gpu_count_sw": 0,
            "panel_count_sw": 0,
            "pressure_low_count_sw": 0,
            "vision_count_sw": 0,
            "motor_ampere_count_sw": 4,
            "cpufreq": "0 (86.00)",
            "gpufreq": "0 (77.00)",
            "panelfreq": "0 (50.00)",
            "visionfreq": "0 (46.00)",
            "pressurefreq": "0 (4.41)",
            "motorfreq": "4 (12.10)"
          }
        },
        {
          "deviceId": "SUK-AL-V3-2.0-10044",
          "data": {
            "cpu_count": 0,
            "gpu_count": 0,
            "panel_count": 0,
            "vision_count": 0,
            "ampere_count": 42,
            "air_pressure_count": 0,
            "device_running": "23:38:40",
            "sorting_running": "20:09:49",
            "cpu_val": "74.00",
            "gpu_val": "78.00",
            "panel_val": "51.00",
            "vision_val": "42.00",
            "ampere_val": "10.03",
            "air_pressure_val": "4.89",
            "cpu_time": "00:00:00",
            "gpu_time": "00:00:00",
            "ampere_time": "00:00:10",
            "air_pressure_time": "00:00:00",
            "panel_time": "00:00:00",
            "vision_time": "00:00:00",
            "motorAmpereThreshold": 7.500000000000002,
            "airPressureLowerValueThreshold": 4,
            "upperPanelThreshold": 60,
            "maxCPUTemperatureThreshold": 87,
            "maxGPUTemperatureThreshold": 80,
            "upperVisionPanelThreshold": 62,
            "cpu_count_sw": 0,
            "gpu_count_sw": 0,
            "panel_count_sw": 0,
            "pressure_low_count_sw": 0,
            "vision_count_sw": 0,
            "motor_ampere_count_sw": 1,
            "cpufreq": "0 (74.00)",
            "gpufreq": "0 (78.00)",
            "panelfreq": "0 (51.00)",
            "visionfreq": "0 (42.00)",
            "pressurefreq": "0 (4.89)",
            "motorfreq": "1 (10.03)"
          }
        },
        {
          "deviceId": "SUK-AL-V3-1.4-10046",
          "data": {
            "cpu_count": 0,
            "gpu_count": 0,
            "panel_count": 0,
            "vision_count": 0,
            "ampere_count": 9,
            "air_pressure_count": 0,
            "device_running": "23:41:06",
            "sorting_running": "21:14:38",
            "cpu_val": "86.00",
            "gpu_val": "76.00",
            "panel_val": "51.00",
            "vision_val": "42.00",
            "ampere_val": "8.77",
            "air_pressure_val": "4.58",
            "cpu_time": "00:00:00",
            "gpu_time": "00:00:00",
            "ampere_time": "00:00:02",
            "air_pressure_time": "00:00:00",
            "panel_time": "00:00:00",
            "vision_time": "00:00:00",
            "motorAmpereThreshold": 6.6999999999999975,
            "airPressureLowerValueThreshold": 4,
            "upperPanelThreshold": 62,
            "maxCPUTemperatureThreshold": 87,
            "maxGPUTemperatureThreshold": 80,
            "upperVisionPanelThreshold": 60,
            "cpu_count_sw": 0,
            "gpu_count_sw": 0,
            "panel_count_sw": 0,
            "pressure_low_count_sw": 0,
            "vision_count_sw": 0,
            "motor_ampere_count_sw": 3,
            "cpufreq": "0 (86.00)",
            "gpufreq": "0 (76.00)",
            "panelfreq": "0 (51.00)",
            "visionfreq": "0 (42.00)",
            "pressurefreq": "0 (4.58)",
            "motorfreq": "3 (8.77)"
          }
        }
      ]
    },
    {
      "orgName": "Banyan Nation",
      "data": [
        {
          "deviceId": "SUKA-AI-V3-2.0-10049",
          "data": {
            "cpu_count": 0,
            "gpu_count": 0,
            "panel_count": 0,
            "vision_count": 0,
            "ampere_count": 5,
            "air_pressure_count": 14,
            "device_running": "23:50:16",
            "sorting_running": "23:46:04",
            "cpu_val": "76.00",
            "gpu_val": "66.00",
            "panel_val": "40.00",
            "vision_val": "36.00",
            "ampere_val": "7.93",
            "air_pressure_val": "3.74",
            "cpu_time": "00:00:00",
            "gpu_time": "00:00:00",
            "ampere_time": "00:00:01",
            "air_pressure_time": "00:00:03",
            "panel_time": "00:00:00",
            "vision_time": "00:00:00",
            "motorAmpereThreshold": 7.499999999999998,
            "airPressureLowerValueThreshold": 4,
            "upperPanelThreshold": 62,
            "maxCPUTemperatureThreshold": 95,
            "maxGPUTemperatureThreshold": 80,
            "upperVisionPanelThreshold": 55,
            "cpu_count_sw": 0,
            "gpu_count_sw": 0,
            "panel_count_sw": 0,
            "pressure_low_count_sw": 14,
            "vision_count_sw": 0,
            "motor_ampere_count_sw": 0,
            "cpufreq": "0 (76.00)",
            "gpufreq": "0 (66.00)",
            "panelfreq": "0 (40.00)",
            "visionfreq": "0 (36.00)",
            "pressurefreq": "14 (3.74)",
            "motorfreq": "0 (7.93)"
          }
        }
      ]
    },
    {
      "orgName": "Vindhya Ceramics",
      "data": [
        {
          "deviceId": "SUK-AL-V3-2.0-10053",
          "data": {
            "cpu_count": 0,
            "gpu_count": 0,
            "panel_count": 0,
            "vision_count": 0,
            "ampere_count": 24,
            "air_pressure_count": 3719,
            "device_running": "22:25:22",
            "sorting_running": "22:00:16",
            "cpu_val": "85.00",
            "gpu_val": "73.00",
            "panel_val": "43.00",
            "vision_val": "41.00",
            "ampere_val": "9.38",
            "air_pressure_val": "0.01",
            "cpu_time": "00:00:00",
            "gpu_time": "00:00:00",
            "ampere_time": "00:00:06",
            "air_pressure_time": "00:15:29",
            "panel_time": "00:00:00",
            "vision_time": "00:00:00",
            "motorAmpereThreshold": 7.199999999999998,
            "airPressureLowerValueThreshold": 4,
            "upperPanelThreshold": 62,
            "maxCPUTemperatureThreshold": 96,
            "maxGPUTemperatureThreshold": 80,
            "upperVisionPanelThreshold": 62,
            "cpu_count_sw": 0,
            "gpu_count_sw": 0,
            "panel_count_sw": 0,
            "pressure_low_count_sw": 188,
            "vision_count_sw": 0,
            "motor_ampere_count_sw": 0,
            "cpufreq": "0 (85.00)",
            "gpufreq": "0 (73.00)",
            "panelfreq": "0 (43.00)",
            "visionfreq": "0 (41.00)",
            "pressurefreq": "188 (0.01)",
            "motorfreq": "0 (9.38)"
          }
        },
        {
          "deviceId": "SUK-AL-V3-2.0-10052",
          "data": {
            "cpu_count": 0,
            "gpu_count": 0,
            "panel_count": 0,
            "vision_count": 0,
            "ampere_count": 982,
            "air_pressure_count": 5686,
            "device_running": "23:38:17",
            "sorting_running": "23:32:33",
            "cpu_val": "86.00",
            "gpu_val": "73.00",
            "panel_val": "44.00",
            "vision_val": "39.00",
            "ampere_val": "8.94",
            "air_pressure_val": "0.04",
            "cpu_time": "00:00:00",
            "gpu_time": "00:00:00",
            "ampere_time": "00:04:05",
            "air_pressure_time": "00:23:41",
            "panel_time": "00:00:00",
            "vision_time": "00:00:00",
            "motorAmpereThreshold": 6.199999999999996,
            "airPressureLowerValueThreshold": 4,
            "upperPanelThreshold": 62,
            "maxCPUTemperatureThreshold": 96,
            "maxGPUTemperatureThreshold": 80,
            "upperVisionPanelThreshold": 60,
            "cpu_count_sw": 0,
            "gpu_count_sw": 0,
            "panel_count_sw": 0,
            "pressure_low_count_sw": 6,
            "vision_count_sw": 0,
            "motor_ampere_count_sw": 0,
            "cpufreq": "0 (86.00)",
            "gpufreq": "0 (73.00)",
            "panelfreq": "0 (44.00)",
            "visionfreq": "0 (39.00)",
            "pressurefreq": "6 (0.04)",
            "motorfreq": "0 (8.94)"
          }
        },
        {
          "deviceId": "SUK-AL-V3-1.4-10054",
          "data": {
            "cpu_count": 0,
            "gpu_count": 0,
            "panel_count": 0,
            "vision_count": 0,
            "ampere_count": 11,
            "air_pressure_count": 5811,
            "device_running": "23:33:28",
            "sorting_running": "22:52:24",
            "cpu_val": "79.00",
            "gpu_val": "72.00",
            "panel_val": "48.00",
            "vision_val": "36.00",
            "ampere_val": "6.25",
            "air_pressure_val": "0.01",
            "cpu_time": "00:00:00",
            "gpu_time": "00:00:00",
            "ampere_time": "00:00:02",
            "air_pressure_time": "00:24:12",
            "panel_time": "00:00:00",
            "vision_time": "00:00:00",
            "motorAmpereThreshold": 6,
            "airPressureLowerValueThreshold": 4,
            "upperPanelThreshold": 62,
            "maxCPUTemperatureThreshold": 96,
            "maxGPUTemperatureThreshold": 80,
            "upperVisionPanelThreshold": 60,
            "cpu_count_sw": 0,
            "gpu_count_sw": 0,
            "panel_count_sw": 0,
            "pressure_low_count_sw": 17,
            "vision_count_sw": 0,
            "motor_ampere_count_sw": 0,
            "cpufreq": "0 (79.00)",
            "gpufreq": "0 (72.00)",
            "panelfreq": "0 (48.00)",
            "visionfreq": "0 (36.00)",
            "pressurefreq": "17 (0.01)",
            "motorfreq": "0 (6.25)"
          }
        }
      ]
    },
    {
      "orgName": "Shree Ram Raghav",
      "data": [
        {
          "deviceId": "SUK-AL-V3-2.0-10055",
          "data": {
            "cpu_count": 2052,
            "gpu_count": 0,
            "panel_count": 0,
            "vision_count": 0,
            "ampere_count": 2,
            "air_pressure_count": 0,
            "device_running": "04:47:47",
            "sorting_running": "01:18:52",
            "cpu_val": "100.00",
            "gpu_val": "75.00",
            "panel_val": "43.00",
            "vision_val": "39.00",
            "ampere_val": "7.30",
            "air_pressure_val": "4.34",
            "cpu_time": "00:08:33",
            "gpu_time": "00:00:00",
            "ampere_time": "00:00:00",
            "air_pressure_time": "00:00:00",
            "panel_time": "00:00:00",
            "vision_time": "00:00:00",
            "motorAmpereThreshold": 6.9999999999999964,
            "airPressureLowerValueThreshold": 4,
            "upperPanelThreshold": 62,
            "maxCPUTemperatureThreshold": 95,
            "maxGPUTemperatureThreshold": 80,
            "upperVisionPanelThreshold": 60,
            "cpu_count_sw": 34,
            "gpu_count_sw": 0,
            "panel_count_sw": 0,
            "pressure_low_count_sw": 0,
            "vision_count_sw": 0,
            "motor_ampere_count_sw": 0,
            "cpufreq": "34 (100.00)",
            "gpufreq": "0 (75.00)",
            "panelfreq": "0 (43.00)",
            "visionfreq": "0 (39.00)",
            "pressurefreq": "0 (4.34)",
            "motorfreq": "0 (7.30)"
          }
        },
        {
          "deviceId": "SUK-AL-V3-1.4-10057",
          "data": {
            "cpu_count": 0,
            "gpu_count": 0,
            "panel_count": 0,
            "vision_count": 0,
            "ampere_count": 2,
            "air_pressure_count": 0,
            "device_running": "23:44:39",
            "sorting_running": "06:13:25",
            "cpu_val": "89.00",
            "gpu_val": "67.00",
            "panel_val": "40.00",
            "vision_val": "33.00",
            "ampere_val": "7.94",
            "air_pressure_val": "4.99",
            "cpu_time": "00:00:00",
            "gpu_time": "00:00:00",
            "ampere_time": "00:00:00",
            "air_pressure_time": "00:00:00",
            "panel_time": "00:00:00",
            "vision_time": "00:00:00",
            "motorAmpereThreshold": 7.0000000000000036,
            "airPressureLowerValueThreshold": 4.5,
            "upperPanelThreshold": 62,
            "maxCPUTemperatureThreshold": 95,
            "maxGPUTemperatureThreshold": 80,
            "upperVisionPanelThreshold": 60,
            "cpu_count_sw": 0,
            "gpu_count_sw": 0,
            "panel_count_sw": 0,
            "pressure_low_count_sw": 0,
            "vision_count_sw": 0,
            "motor_ampere_count_sw": 0,
            "cpufreq": "0 (89.00)",
            "gpufreq": "0 (67.00)",
            "panelfreq": "0 (40.00)",
            "visionfreq": "0 (33.00)",
            "pressurefreq": "0 (4.99)",
            "motorfreq": "0 (7.94)"
          }
        },
        {
          "deviceId": "SUK-AL-V3-2.0-10056",
          "data": {
            "cpu_count": 0,
            "gpu_count": 0,
            "panel_count": 0,
            "vision_count": 0,
            "ampere_count": 0,
            "air_pressure_count": 243,
            "device_running": "22:16:20",
            "sorting_running": "05:52:30",
            "cpu_val": "94.00",
            "gpu_val": "70.00",
            "panel_val": "45.00",
            "vision_val": "39.00",
            "ampere_val": "6.91",
            "air_pressure_val": "0.00",
            "cpu_time": "00:00:00",
            "gpu_time": "00:00:00",
            "ampere_time": "00:00:00",
            "air_pressure_time": "00:01:00",
            "panel_time": "00:00:00",
            "vision_time": "00:00:00",
            "motorAmpereThreshold": 7.5,
            "airPressureLowerValueThreshold": 4,
            "upperPanelThreshold": 62,
            "maxCPUTemperatureThreshold": 95,
            "maxGPUTemperatureThreshold": 80,
            "upperVisionPanelThreshold": 60,
            "cpu_count_sw": 0,
            "gpu_count_sw": 0,
            "panel_count_sw": 0,
            "pressure_low_count_sw": 0,
            "vision_count_sw": 0,
            "motor_ampere_count_sw": 0,
            "cpufreq": "0 (94.00)",
            "gpufreq": "0 (70.00)",
            "panelfreq": "0 (45.00)",
            "visionfreq": "0 (39.00)",
            "pressurefreq": "0 (0.00)",
            "motorfreq": "0 (6.91)"
          }
        }
      ]
    },
    {
      "orgName": "Re Sustainability Ltd",
      "data": [
        {
          "deviceId": "SUK-AI-V3-1.4-10070",
          "data": {
            "cpu_count": 0,
            "gpu_count": 0,
            "panel_count": 0,
            "vision_count": 0,
            "ampere_count": 0,
            "air_pressure_count": 0,
            "device_running": "00:00:00",
            "sorting_running": "00:00:00",
            "cpu_time": "00:00:00",
            "gpu_time": "00:00:00",
            "ampere_time": "00:00:00",
            "air_pressure_time": "00:00:00",
            "panel_time": "00:00:00",
            "vision_time": "00:00:00",
            "motorAmpereThreshold": 7.500000000000002,
            "airPressureLowerValueThreshold": 4.5,
            "upperPanelThreshold": 60,
            "maxCPUTemperatureThreshold": 85,
            "maxGPUTemperatureThreshold": 75,
            "upperVisionPanelThreshold": 55,
            "cpu_count_sw": 0,
            "gpu_count_sw": 0,
            "panel_count_sw": 0,
            "pressure_low_count_sw": 0,
            "vision_count_sw": 0,
            "motor_ampere_count_sw": 0,
            "cpufreq": "0 (undefined)",
            "gpufreq": "0 (undefined)",
            "panelfreq": "0 (undefined)",
            "visionfreq": "0 (undefined)",
            "pressurefreq": "0 (undefined)",
            "motorfreq": "0 (undefined)"
          }
        }
      ]
    },
    {
      "orgName": "Starlite",
      "data": [
        {
          "deviceId": "SUK-AI-V3-2.0-10060",
          "data": {
            "cpu_count": 0,
            "gpu_count": 0,
            "panel_count": 0,
            "vision_count": 0,
            "ampere_count": 5,
            "air_pressure_count": 5189,
            "device_running": "05:09:27",
            "sorting_running": "03:13:03",
            "cpu_val": "72.00",
            "gpu_val": "64.00",
            "panel_val": "40.00",
            "vision_val": "41.00",
            "ampere_val": "7.77",
            "air_pressure_val": "0.74",
            "cpu_time": "00:00:00",
            "gpu_time": "00:00:00",
            "ampere_time": "00:00:01",
            "air_pressure_time": "00:21:37",
            "panel_time": "00:00:00",
            "vision_time": "00:00:00",
            "motorAmpereThreshold": 7.5,
            "airPressureLowerValueThreshold": 4,
            "upperPanelThreshold": 60,
            "maxCPUTemperatureThreshold": 90,
            "maxGPUTemperatureThreshold": 80,
            "upperVisionPanelThreshold": 60,
            "cpu_count_sw": 0,
            "gpu_count_sw": 0,
            "panel_count_sw": 0,
            "pressure_low_count_sw": 1,
            "vision_count_sw": 0,
            "motor_ampere_count_sw": 0,
            "cpufreq": "0 (72.00)",
            "gpufreq": "0 (64.00)",
            "panelfreq": "0 (40.00)",
            "visionfreq": "0 (41.00)",
            "pressurefreq": "1 (0.74)",
            "motorfreq": "0 (7.77)"
          }
        }
      ]
    },
    {
      "orgName": "Jaipuria Bevearges & Food Industries Pvt Ltd",
      "data": [
        {
          "deviceId": "SUK-AI-V3-2.0-10063",
          "data": {
            "cpu_count": 0,
            "gpu_count": 0,
            "panel_count": 0,
            "vision_count": 0,
            "ampere_count": 0,
            "air_pressure_count": 0,
            "device_running": "00:00:00",
            "sorting_running": "00:00:00",
            "cpu_time": "00:00:00",
            "gpu_time": "00:00:00",
            "ampere_time": "00:00:00",
            "air_pressure_time": "00:00:00",
            "panel_time": "00:00:00",
            "vision_time": "00:00:00",
            "motorAmpereThreshold": 7.5,
            "airPressureLowerValueThreshold": 4.5,
            "upperPanelThreshold": 60,
            "maxCPUTemperatureThreshold": 85,
            "maxGPUTemperatureThreshold": 75,
            "upperVisionPanelThreshold": 55,
            "cpu_count_sw": 0,
            "gpu_count_sw": 0,
            "panel_count_sw": 0,
            "pressure_low_count_sw": 0,
            "vision_count_sw": 0,
            "motor_ampere_count_sw": 0,
            "cpufreq": "0 (undefined)",
            "gpufreq": "0 (undefined)",
            "panelfreq": "0 (undefined)",
            "visionfreq": "0 (undefined)",
            "pressurefreq": "0 (undefined)",
            "motorfreq": "0 (undefined)"
          }
        },
        {
          "deviceId": "SUK-AI-V3-2.0-10062",
          "data": {
            "cpu_count": 0,
            "gpu_count": 0,
            "panel_count": 0,
            "vision_count": 0,
            "ampere_count": 0,
            "air_pressure_count": 0,
            "device_running": "00:00:00",
            "sorting_running": "00:00:00",
            "cpu_time": "00:00:00",
            "gpu_time": "00:00:00",
            "ampere_time": "00:00:00",
            "air_pressure_time": "00:00:00",
            "panel_time": "00:00:00",
            "vision_time": "00:00:00",
            "motorAmpereThreshold": 7.499999999999995,
            "airPressureLowerValueThreshold": 4.5,
            "upperPanelThreshold": 55,
            "maxCPUTemperatureThreshold": 85,
            "maxGPUTemperatureThreshold": 75,
            "upperVisionPanelThreshold": 60,
            "cpu_count_sw": 0,
            "gpu_count_sw": 0,
            "panel_count_sw": 0,
            "pressure_low_count_sw": 0,
            "vision_count_sw": 0,
            "motor_ampere_count_sw": 0,
            "cpufreq": "0 (undefined)",
            "gpufreq": "0 (undefined)",
            "panelfreq": "0 (undefined)",
            "visionfreq": "0 (undefined)",
            "pressurefreq": "0 (undefined)",
            "motorfreq": "0 (undefined)"
          }
        },
        {
          "deviceId": "SUK-AI-V3-1.4-10064",
          "data": {
            "cpu_count": 0,
            "gpu_count": 0,
            "panel_count": 0,
            "vision_count": 0,
            "ampere_count": 0,
            "air_pressure_count": 0,
            "device_running": "00:00:00",
            "sorting_running": "00:00:00",
            "cpu_time": "00:00:00",
            "gpu_time": "00:00:00",
            "ampere_time": "00:00:00",
            "air_pressure_time": "00:00:00",
            "panel_time": "00:00:00",
            "vision_time": "00:00:00",
            "motorAmpereThreshold": 7.499999999999995,
            "airPressureLowerValueThreshold": 4.5,
            "upperPanelThreshold": 62,
            "maxCPUTemperatureThreshold": 85,
            "maxGPUTemperatureThreshold": 80,
            "upperVisionPanelThreshold": 60,
            "cpu_count_sw": 0,
            "gpu_count_sw": 0,
            "panel_count_sw": 0,
            "pressure_low_count_sw": 0,
            "vision_count_sw": 0,
            "motor_ampere_count_sw": 0,
            "cpufreq": "0 (undefined)",
            "gpufreq": "0 (undefined)",
            "panelfreq": "0 (undefined)",
            "visionfreq": "0 (undefined)",
            "pressurefreq": "0 (undefined)",
            "motorfreq": "0 (undefined)"
          }
        }
      ]
    },
    {
      "orgName": "Project Uday",
      "data": [
        {
          "deviceId": "SAN-AI-V1-1.0-10033",
          "data": {
            "cpu_count": 10733,
            "gpu_count": 0,
            "panel_count": 0,
            "vision_count": 0,
            "ampere_count": 142,
            "air_pressure_count": 245994,
            "device_running": "23:05:54",
            "sorting_running": "03:02:38",
            "cpu_val": "90.00",
            "gpu_val": "75.00",
            "panel_val": "52.00",
            "vision_val": "46.00",
            "ampere_val": "15.25",
            "air_pressure_val": "0.00",
            "cpu_time": "00:44:43",
            "gpu_time": "00:00:00",
            "ampere_time": "00:00:35",
            "air_pressure_time": "17:04:58",
            "panel_time": "00:00:00",
            "vision_time": "00:00:00",
            "motorAmpereThreshold": 7.5,
            "airPressureLowerValueThreshold": 4.2,
            "upperPanelThreshold": 62,
            "maxCPUTemperatureThreshold": 80,
            "maxGPUTemperatureThreshold": 80,
            "upperVisionPanelThreshold": 55,
            "cpu_count_sw": 0,
            "gpu_count_sw": 0,
            "panel_count_sw": 55,
            "pressure_low_count_sw": 0,
            "vision_count_sw": 0,
            "motor_ampere_count_sw": 3,
            "cpufreq": "0 (90.00)",
            "gpufreq": "0 (75.00)",
            "panelfreq": "55 (52.00)",
            "visionfreq": "0 (46.00)",
            "pressurefreq": "0 (0.00)",
            "motorfreq": "3 (15.25)"
          }
        }
      ]
    },
    {
      "orgName": "Poddar",
      "data": [
        {
          "deviceId": "SUK-AI-V3-1.4-10061",
          "data": {
            "cpu_count": 0,
            "gpu_count": 0,
            "panel_count": 0,
            "vision_count": 0,
            "ampere_count": 0,
            "air_pressure_count": 0,
            "device_running": "00:00:00",
            "sorting_running": "00:00:00",
            "cpu_time": "00:00:00",
            "gpu_time": "00:00:00",
            "ampere_time": "00:00:00",
            "air_pressure_time": "00:00:00",
            "panel_time": "00:00:00",
            "vision_time": "00:00:00",
            "motorAmpereThreshold": 6,
            "airPressureLowerValueThreshold": 4,
            "upperPanelThreshold": 62,
            "maxCPUTemperatureThreshold": 60,
            "maxGPUTemperatureThreshold": 80,
            "upperVisionPanelThreshold": 60,
            "cpu_count_sw": 0,
            "gpu_count_sw": 0,
            "panel_count_sw": 0,
            "pressure_low_count_sw": 0,
            "vision_count_sw": 0,
            "motor_ampere_count_sw": 0,
            "cpufreq": "0 (undefined)",
            "gpufreq": "0 (undefined)",
            "panelfreq": "0 (undefined)",
            "visionfreq": "0 (undefined)",
            "pressurefreq": "0 (undefined)",
            "motorfreq": "0 (undefined)"
          }
        }
      ]
    },
    {
      "orgName": "Meta",
      "data": [
        {
          "deviceId": "SUK-AI-V3-2.0-10075",
          "data": {
            "cpu_count": 0,
            "gpu_count": 0,
            "panel_count": 2,
            "vision_count": 2,
            "ampere_count": 10265,
            "air_pressure_count": 3466,
            "device_running": "01:24:44",
            "sorting_running": "00:00:00",
            "cpu_val": "94.00",
            "gpu_val": "62.00",
            "panel_val": "236.00",
            "vision_val": "236.00",
            "ampere_val": "50.00",
            "air_pressure_val": "0.00",
            "cpu_time": "00:00:00",
            "gpu_time": "00:00:00",
            "ampere_time": "00:42:46",
            "air_pressure_time": "00:14:26",
            "panel_time": "00:00:00",
            "vision_time": "00:00:00",
            "motorAmpereThreshold": 7.500000000000002,
            "airPressureLowerValueThreshold": 4,
            "upperPanelThreshold": 62,
            "maxCPUTemperatureThreshold": 100,
            "maxGPUTemperatureThreshold": 80,
            "upperVisionPanelThreshold": 60,
            "cpu_count_sw": 0,
            "gpu_count_sw": 0,
            "panel_count_sw": 17,
            "pressure_low_count_sw": 1,
            "vision_count_sw": 0,
            "motor_ampere_count_sw": 6,
            "cpufreq": "0 (94.00)",
            "gpufreq": "0 (62.00)",
            "panelfreq": "17 (236.00)",
            "visionfreq": "0 (236.00)",
            "pressurefreq": "1 (0.00)",
            "motorfreq": "6 (50.00)"
          }
        },
        {
          "deviceId": "SUK-AI-V3-2.0-10076",
          "data": {
            "cpu_count": 0,
            "gpu_count": 0,
            "panel_count": 18,
            "vision_count": 18,
            "ampere_count": 0,
            "air_pressure_count": 272144,
            "device_running": "18:53:56",
            "sorting_running": "15:09:28",
            "cpu_val": "97.00",
            "gpu_val": "69.00",
            "panel_val": "236.00",
            "vision_val": "236.00",
            "ampere_val": "0.00",
            "air_pressure_val": "0.00",
            "cpu_time": "00:00:00",
            "gpu_time": "00:00:00",
            "ampere_time": "00:00:00",
            "air_pressure_time": "18:53:56",
            "panel_time": "00:00:04",
            "vision_time": "00:00:04",
            "motorAmpereThreshold": 7.500000000000002,
            "airPressureLowerValueThreshold": 4,
            "upperPanelThreshold": 62,
            "maxCPUTemperatureThreshold": 99,
            "maxGPUTemperatureThreshold": 80,
            "upperVisionPanelThreshold": 60,
            "cpu_count_sw": 0,
            "gpu_count_sw": 0,
            "panel_count_sw": 34,
            "pressure_low_count_sw": 0,
            "vision_count_sw": 0,
            "motor_ampere_count_sw": 0,
            "cpufreq": "0 (97.00)",
            "gpufreq": "0 (69.00)",
            "panelfreq": "34 (236.00)",
            "visionfreq": "0 (236.00)",
            "pressurefreq": "0 (0.00)",
            "motorfreq": "0 (0.00)"
          }
        }
      ]
    }
  ]