module.exports = 
[
  {
    "orgName": "Dodhia Synthetic Limited",
    "data": [
      {
        "deviceId": "DSL_SUKA_1",
        "data": {
          "cpu_count": 0,
          "gpu_count": 0,
          "panel_count": 0,
          "vision_count": 0,
          "ampere_count": 0,
          "air_pressure_count": 0,
          "device_running": "00:00:00",
          "sorting_running": "00:00:00",
          "cpu_time": "00:00:00",
          "gpu_time": "00:00:00",
          "ampere_time": "00:00:00",
          "air_pressure_time": "00:00:00",
          "panel_time": "00:00:00",
          "vision_time": "00:00:00",
          "motorAmpereThreshold": 5.999999999999999,
          "airPressureLowerValueThreshold": 4.1,
          "upperPanelThreshold": 50,
          "maxCPUTemperatureThreshold": 90,
          "maxGPUTemperatureThreshold": 90,
          "upperVisionPanelThreshold": 50,
          "cpu_count_sw": 0,
          "gpu_count_sw": 0,
          "panel_count_sw": 0,
          "pressure_low_count_sw": 15,
          "vision_count_sw": 0,
          "motor_ampere_count_sw": 0,
          "cpufreq": "0 (undefined)",
          "gpufreq": "0 (undefined)",
          "panelfreq": "0 (undefined)",
          "visionfreq": "0 (undefined)",
          "pressurefreq": "15 (undefined)",
          "motorfreq": "0 (undefined)"
        }
      },
      {
        "deviceId": "DSL_SUKA_2",
        "data": {
          "cpu_count": 0,
          "gpu_count": 0,
          "panel_count": 0,
          "vision_count": 0,
          "ampere_count": 0,
          "air_pressure_count": 0,
          "device_running": "00:00:00",
          "sorting_running": "00:00:00",
          "cpu_time": "00:00:00",
          "gpu_time": "00:00:00",
          "ampere_time": "00:00:00",
          "air_pressure_time": "00:00:00",
          "panel_time": "00:00:00",
          "vision_time": "00:00:00",
          "motorAmpereThreshold": 6,
          "airPressureLowerValueThreshold": 4.5,
          "upperPanelThreshold": 50,
          "maxCPUTemperatureThreshold": 90,
          "maxGPUTemperatureThreshold": 90,
          "upperVisionPanelThreshold": 55,
          "cpu_count_sw": 0,
          "gpu_count_sw": 0,
          "panel_count_sw": 0,
          "pressure_low_count_sw": 1,
          "vision_count_sw": 0,
          "motor_ampere_count_sw": 0,
          "cpufreq": "0 (undefined)",
          "gpufreq": "0 (undefined)",
          "panelfreq": "0 (undefined)",
          "visionfreq": "0 (undefined)",
          "pressurefreq": "1 (undefined)",
          "motorfreq": "0 (undefined)"
        }
      },
      {
        "deviceId": "dsl-su14-10031",
        "data": {
          "cpu_count": 0,
          "gpu_count": 0,
          "panel_count": 0,
          "vision_count": 0,
          "ampere_count": 10,
          "air_pressure_count": 0,
          "device_running": "22:15:47",
          "sorting_running": "18:33:58",
          "cpu_val": "83.00",
          "gpu_val": "70.00",
          "panel_val": "51.00",
          "vision_val": "34.00",
          "ampere_val": "8.25",
          "air_pressure_val": "4.34",
          "cpu_time": "00:00:00",
          "gpu_time": "00:00:00",
          "ampere_time": "00:00:02",
          "air_pressure_time": "00:00:00",
          "panel_time": "00:00:00",
          "vision_time": "00:00:00",
          "motorAmpereThreshold": 7.799999999999999,
          "airPressureLowerValueThreshold": 4,
          "upperPanelThreshold": 62,
          "maxCPUTemperatureThreshold": 92,
          "maxGPUTemperatureThreshold": 80,
          "upperVisionPanelThreshold": 60,
          "cpu_count_sw": 0,
          "gpu_count_sw": 0,
          "panel_count_sw": 0,
          "pressure_low_count_sw": 0,
          "vision_count_sw": 0,
          "motor_ampere_count_sw": 4,
          "cpufreq": "0 (83.00)",
          "gpufreq": "0 (70.00)",
          "panelfreq": "0 (51.00)",
          "visionfreq": "0 (34.00)",
          "pressurefreq": "0 (4.34)",
          "motorfreq": "4 (8.25)"
        }
      },
      {
        "deviceId": "dsl-su20-10030",
        "data": {
          "cpu_count": 0,
          "gpu_count": 0,
          "panel_count": 0,
          "vision_count": 0,
          "ampere_count": 8,
          "air_pressure_count": 7,
          "device_running": "22:04:10",
          "sorting_running": "17:37:20",
          "cpu_val": "82.00",
          "gpu_val": "73.00",
          "panel_val": "50.00",
          "vision_val": "42.00",
          "ampere_val": "9.96",
          "air_pressure_val": "2.31",
          "cpu_time": "00:00:00",
          "gpu_time": "00:00:00",
          "ampere_time": "00:00:02",
          "air_pressure_time": "00:00:01",
          "panel_time": "00:00:00",
          "vision_time": "00:00:00",
          "motorAmpereThreshold": 7.499999999999998,
          "airPressureLowerValueThreshold": 4,
          "upperPanelThreshold": 62,
          "maxCPUTemperatureThreshold": 90,
          "maxGPUTemperatureThreshold": 80,
          "upperVisionPanelThreshold": 60,
          "cpu_count_sw": 0,
          "gpu_count_sw": 0,
          "panel_count_sw": 0,
          "pressure_low_count_sw": 6,
          "vision_count_sw": 0,
          "motor_ampere_count_sw": 2,
          "cpufreq": "0 (82.00)",
          "gpufreq": "0 (73.00)",
          "panelfreq": "0 (50.00)",
          "visionfreq": "0 (42.00)",
          "pressurefreq": "6 (2.31)",
          "motorfreq": "2 (9.96)"
        }
      },
      {
        "deviceId": "dsl-su20-10029",
        "data": {
          "cpu_count": 0,
          "gpu_count": 0,
          "panel_count": 0,
          "vision_count": 0,
          "ampere_count": 3,
          "air_pressure_count": 63,
          "device_running": "22:26:58",
          "sorting_running": "20:14:58",
          "cpu_val": "68.00",
          "gpu_val": "63.00",
          "panel_val": "42.00",
          "vision_val": "39.00",
          "ampere_val": "7.83",
          "air_pressure_val": "3.66",
          "cpu_time": "00:00:00",
          "gpu_time": "00:00:00",
          "ampere_time": "00:00:00",
          "air_pressure_time": "00:00:15",
          "panel_time": "00:00:00",
          "vision_time": "00:00:00",
          "motorAmpereThreshold": 7.499999999999998,
          "airPressureLowerValueThreshold": 4,
          "upperPanelThreshold": 62,
          "maxCPUTemperatureThreshold": 92,
          "maxGPUTemperatureThreshold": 80,
          "upperVisionPanelThreshold": 60,
          "cpu_count_sw": 0,
          "gpu_count_sw": 0,
          "panel_count_sw": 0,
          "pressure_low_count_sw": 66,
          "vision_count_sw": 0,
          "motor_ampere_count_sw": 0,
          "cpufreq": "0 (68.00)",
          "gpufreq": "0 (63.00)",
          "panelfreq": "0 (42.00)",
          "visionfreq": "0 (39.00)",
          "pressurefreq": "66 (3.66)",
          "motorfreq": "0 (7.83)"
        }
      },
      {
        "deviceId": "dsl-su20-10028",
        "data": {
          "cpu_count": 0,
          "gpu_count": 0,
          "panel_count": 0,
          "vision_count": 0,
          "ampere_count": 0,
          "air_pressure_count": 0,
          "device_running": "22:14:27",
          "sorting_running": "17:35:56",
          "cpu_val": "70.00",
          "gpu_val": "68.00",
          "panel_val": "39.00",
          "vision_val": "41.00",
          "ampere_val": "7.42",
          "air_pressure_val": "4.51",
          "cpu_time": "00:00:00",
          "gpu_time": "00:00:00",
          "ampere_time": "00:00:00",
          "air_pressure_time": "00:00:00",
          "panel_time": "00:00:00",
          "vision_time": "00:00:00",
          "motorAmpereThreshold": 7.499999999999995,
          "airPressureLowerValueThreshold": 4,
          "upperPanelThreshold": 62,
          "maxCPUTemperatureThreshold": 90,
          "maxGPUTemperatureThreshold": 80,
          "upperVisionPanelThreshold": 60,
          "cpu_count_sw": 0,
          "gpu_count_sw": 0,
          "panel_count_sw": 0,
          "pressure_low_count_sw": 0,
          "vision_count_sw": 0,
          "motor_ampere_count_sw": 0,
          "cpufreq": "0 (70.00)",
          "gpufreq": "0 (68.00)",
          "panelfreq": "0 (39.00)",
          "visionfreq": "0 (41.00)",
          "pressurefreq": "0 (4.51)",
          "motorfreq": "0 (7.42)"
        }
      },
      {
        "deviceId": "dsl-su20-10027",
        "data": {
          "cpu_count": 0,
          "gpu_count": 0,
          "panel_count": 0,
          "vision_count": 0,
          "ampere_count": 0,
          "air_pressure_count": 1,
          "device_running": "22:11:32",
          "sorting_running": "17:32:43",
          "cpu_val": "81.00",
          "gpu_val": "75.00",
          "panel_val": "48.00",
          "vision_val": "39.00",
          "ampere_val": "7.18",
          "air_pressure_val": "2.66",
          "cpu_time": "00:00:00",
          "gpu_time": "00:00:00",
          "ampere_time": "00:00:00",
          "air_pressure_time": "00:00:00",
          "panel_time": "00:00:00",
          "vision_time": "00:00:00",
          "motorAmpereThreshold": 7.499999999999995,
          "airPressureLowerValueThreshold": 4,
          "upperPanelThreshold": 62,
          "maxCPUTemperatureThreshold": 90,
          "maxGPUTemperatureThreshold": 80,
          "upperVisionPanelThreshold": 60,
          "cpu_count_sw": 0,
          "gpu_count_sw": 0,
          "panel_count_sw": 0,
          "pressure_low_count_sw": 1,
          "vision_count_sw": 0,
          "motor_ampere_count_sw": 0,
          "cpufreq": "0 (81.00)",
          "gpufreq": "0 (75.00)",
          "panelfreq": "0 (48.00)",
          "visionfreq": "0 (39.00)",
          "pressurefreq": "1 (2.66)",
          "motorfreq": "0 (7.18)"
        }
      }
    ]
  },
  {
    "orgName": "Pashupati Polyplex Pvt Ltd",
    "data": [
      {
        "deviceId": "PPP_SUKA_1",
        "data": {
          "cpu_count": 0,
          "gpu_count": 0,
          "panel_count": 0,
          "vision_count": 0,
          "ampere_count": 0,
          "air_pressure_count": 0,
          "device_running": "00:00:00",
          "sorting_running": "00:00:00",
          "cpu_time": "00:00:00",
          "gpu_time": "00:00:00",
          "ampere_time": "00:00:00",
          "air_pressure_time": "00:00:00",
          "panel_time": "00:00:00",
          "vision_time": "00:00:00",
          "motorAmpereThreshold": 5.999999999999999,
          "airPressureLowerValueThreshold": 4,
          "upperPanelThreshold": 50,
          "maxCPUTemperatureThreshold": 95,
          "maxGPUTemperatureThreshold": 95,
          "upperVisionPanelThreshold": 50,
          "cpu_count_sw": 0,
          "gpu_count_sw": 0,
          "panel_count_sw": 0,
          "pressure_low_count_sw": 0,
          "vision_count_sw": 0,
          "motor_ampere_count_sw": 0,
          "cpufreq": "0 (undefined)",
          "gpufreq": "0 (undefined)",
          "panelfreq": "0 (undefined)",
          "visionfreq": "0 (undefined)",
          "pressurefreq": "0 (undefined)",
          "motorfreq": "0 (undefined)"
        }
      },
      {
        "deviceId": "PPP_SUKA_2",
        "data": {
          "cpu_count": 0,
          "gpu_count": 0,
          "panel_count": 0,
          "vision_count": 0,
          "ampere_count": 0,
          "air_pressure_count": 0,
          "device_running": "00:00:00",
          "sorting_running": "00:00:00",
          "cpu_time": "00:00:00",
          "gpu_time": "00:00:00",
          "ampere_time": "00:00:00",
          "air_pressure_time": "00:00:00",
          "panel_time": "00:00:00",
          "vision_time": "00:00:00",
          "motorAmpereThreshold": 5.999999999999999,
          "airPressureLowerValueThreshold": 4,
          "upperPanelThreshold": 50,
          "maxCPUTemperatureThreshold": 90,
          "maxGPUTemperatureThreshold": 90,
          "upperVisionPanelThreshold": 50,
          "cpu_count_sw": 0,
          "gpu_count_sw": 0,
          "panel_count_sw": 0,
          "pressure_low_count_sw": 0,
          "vision_count_sw": 0,
          "motor_ampere_count_sw": 0,
          "cpufreq": "0 (undefined)",
          "gpufreq": "0 (undefined)",
          "panelfreq": "0 (undefined)",
          "visionfreq": "0 (undefined)",
          "pressurefreq": "0 (undefined)",
          "motorfreq": "0 (undefined)"
        }
      },
      {
        "deviceId": "PPP_SUKA_3",
        "data": {
          "cpu_count": 0,
          "gpu_count": 0,
          "panel_count": 0,
          "vision_count": 0,
          "ampere_count": 0,
          "air_pressure_count": 0,
          "device_running": "00:00:00",
          "sorting_running": "00:00:00",
          "cpu_time": "00:00:00",
          "gpu_time": "00:00:00",
          "ampere_time": "00:00:00",
          "air_pressure_time": "00:00:00",
          "panel_time": "00:00:00",
          "vision_time": "00:00:00",
          "motorAmpereThreshold": 5.999999999999999,
          "airPressureLowerValueThreshold": 4,
          "upperPanelThreshold": 50,
          "maxCPUTemperatureThreshold": 90,
          "maxGPUTemperatureThreshold": 90,
          "upperVisionPanelThreshold": 50,
          "cpu_count_sw": 0,
          "gpu_count_sw": 0,
          "panel_count_sw": 0,
          "pressure_low_count_sw": 0,
          "vision_count_sw": 0,
          "motor_ampere_count_sw": 0,
          "cpufreq": "0 (undefined)",
          "gpufreq": "0 (undefined)",
          "panelfreq": "0 (undefined)",
          "visionfreq": "0 (undefined)",
          "pressurefreq": "0 (undefined)",
          "motorfreq": "0 (undefined)"
        }
      }
    ]
  },
  {
    "orgName": "Ishitva Robotic Systems",
    "data": [
      {
        "deviceId": "CHANGODAR_2_MTR",
        "data": {
          "cpu_count": 0,
          "gpu_count": 0,
          "panel_count": 0,
          "vision_count": 0,
          "ampere_count": 0,
          "air_pressure_count": 0,
          "device_running": "00:00:00",
          "sorting_running": "00:00:00",
          "cpu_time": "00:00:00",
          "gpu_time": "00:00:00",
          "ampere_time": "00:00:00",
          "air_pressure_time": "00:00:00",
          "panel_time": "00:00:00",
          "vision_time": "00:00:00",
          "motorAmpereThreshold": 7.800000000000001,
          "airPressureLowerValueThreshold": 4.5,
          "upperPanelThreshold": 50,
          "maxCPUTemperatureThreshold": 100,
          "maxGPUTemperatureThreshold": 90,
          "upperVisionPanelThreshold": 55,
          "cpu_count_sw": 0,
          "gpu_count_sw": 0,
          "panel_count_sw": 0,
          "pressure_low_count_sw": 0,
          "vision_count_sw": 0,
          "motor_ampere_count_sw": 0,
          "cpufreq": "0 (undefined)",
          "gpufreq": "0 (undefined)",
          "panelfreq": "0 (undefined)",
          "visionfreq": "0 (undefined)",
          "pressurefreq": "0 (undefined)",
          "motorfreq": "0 (undefined)"
        }
      },
      {
        "deviceId": "PLAST-VISION",
        "data": {
          "cpu_count": 0,
          "gpu_count": 0,
          "panel_count": 0,
          "vision_count": 0,
          "ampere_count": 0,
          "air_pressure_count": 0,
          "device_running": "00:00:00",
          "sorting_running": "00:00:00",
          "cpu_time": "00:00:00",
          "gpu_time": "00:00:00",
          "ampere_time": "00:00:00",
          "air_pressure_time": "00:00:00",
          "panel_time": "00:00:00",
          "vision_time": "00:00:00",
          "motorAmpereThreshold": 6,
          "airPressureLowerValueThreshold": 4.5,
          "upperPanelThreshold": 50,
          "maxCPUTemperatureThreshold": 95,
          "maxGPUTemperatureThreshold": 90,
          "upperVisionPanelThreshold": 55,
          "cpu_count_sw": 0,
          "gpu_count_sw": 0,
          "panel_count_sw": 0,
          "pressure_low_count_sw": 0,
          "vision_count_sw": 0,
          "motor_ampere_count_sw": 0,
          "cpufreq": "0 (undefined)",
          "gpufreq": "0 (undefined)",
          "panelfreq": "0 (undefined)",
          "visionfreq": "0 (undefined)",
          "pressurefreq": "0 (undefined)",
          "motorfreq": "0 (undefined)"
        }
      },
      {
        "deviceId": "SRICHAKRA_SUKA_1",
        "data": {
          "cpu_count": 0,
          "gpu_count": 0,
          "panel_count": 0,
          "vision_count": 0,
          "ampere_count": 0,
          "air_pressure_count": 0,
          "device_running": "00:00:00",
          "sorting_running": "00:00:00",
          "cpu_time": "00:00:00",
          "gpu_time": "00:00:00",
          "ampere_time": "00:00:00",
          "air_pressure_time": "00:00:00",
          "panel_time": "00:00:00",
          "vision_time": "00:00:00",
          "motorAmpereThreshold": 7.999999999999993,
          "airPressureLowerValueThreshold": 4.5,
          "upperPanelThreshold": 62,
          "maxCPUTemperatureThreshold": 90,
          "maxGPUTemperatureThreshold": 80,
          "upperVisionPanelThreshold": 55,
          "cpu_count_sw": 0,
          "gpu_count_sw": 0,
          "panel_count_sw": 0,
          "pressure_low_count_sw": 0,
          "vision_count_sw": 0,
          "motor_ampere_count_sw": 0,
          "cpufreq": "0 (undefined)",
          "gpufreq": "0 (undefined)",
          "panelfreq": "0 (undefined)",
          "visionfreq": "0 (undefined)",
          "pressurefreq": "0 (undefined)",
          "motorfreq": "0 (undefined)"
        }
      },
      {
        "deviceId": "test",
        "data": {
          "cpu_count": 0,
          "gpu_count": 0,
          "panel_count": 0,
          "vision_count": 0,
          "ampere_count": 0,
          "air_pressure_count": 0,
          "device_running": "00:00:00",
          "sorting_running": "00:00:00",
          "cpu_time": "00:00:00",
          "gpu_time": "00:00:00",
          "ampere_time": "00:00:00",
          "air_pressure_time": "00:00:00",
          "panel_time": "00:00:00",
          "vision_time": "00:00:00",
          "motorAmpereThreshold": 6,
          "airPressureLowerValueThreshold": 4.5,
          "upperPanelThreshold": 62,
          "maxCPUTemperatureThreshold": 90,
          "maxGPUTemperatureThreshold": 80,
          "upperVisionPanelThreshold": 55,
          "cpu_count_sw": 0,
          "gpu_count_sw": 0,
          "panel_count_sw": 0,
          "pressure_low_count_sw": 1,
          "vision_count_sw": 0,
          "motor_ampere_count_sw": 0,
          "cpufreq": "0 (undefined)",
          "gpufreq": "0 (undefined)",
          "panelfreq": "0 (undefined)",
          "visionfreq": "0 (undefined)",
          "pressurefreq": "1 (undefined)",
          "motorfreq": "0 (undefined)"
        }
      },
      {
        "deviceId": "PLASTVISION_1.4M",
        "data": {
          "cpu_count": 0,
          "gpu_count": 0,
          "panel_count": 0,
          "vision_count": 0,
          "ampere_count": 0,
          "air_pressure_count": 0,
          "device_running": "00:00:00",
          "sorting_running": "00:00:00",
          "cpu_time": "00:00:00",
          "gpu_time": "00:00:00",
          "ampere_time": "00:00:00",
          "air_pressure_time": "00:00:00",
          "panel_time": "00:00:00",
          "vision_time": "00:00:00",
          "motorAmpereThreshold": 7.000000000000002,
          "airPressureLowerValueThreshold": 4.2,
          "upperPanelThreshold": 60,
          "maxCPUTemperatureThreshold": 100,
          "maxGPUTemperatureThreshold": 90,
          "upperVisionPanelThreshold": 65,
          "cpu_count_sw": 0,
          "gpu_count_sw": 0,
          "panel_count_sw": 0,
          "pressure_low_count_sw": 0,
          "vision_count_sw": 0,
          "motor_ampere_count_sw": 0,
          "cpufreq": "0 (undefined)",
          "gpufreq": "0 (undefined)",
          "panelfreq": "0 (undefined)",
          "visionfreq": "0 (undefined)",
          "pressurefreq": "0 (undefined)",
          "motorfreq": "0 (undefined)"
        }
      },
      {
        "deviceId": "black_sanjivani",
        "data": {
          "cpu_count": 0,
          "gpu_count": 0,
          "panel_count": 0,
          "vision_count": 0,
          "ampere_count": 0,
          "air_pressure_count": 0,
          "device_running": "00:00:00",
          "sorting_running": "00:00:00",
          "cpu_time": "00:00:00",
          "gpu_time": "00:00:00",
          "ampere_time": "00:00:00",
          "air_pressure_time": "00:00:00",
          "panel_time": "00:00:00",
          "vision_time": "00:00:00",
          "motorAmpereThreshold": 7.5,
          "airPressureLowerValueThreshold": 4.2,
          "upperPanelThreshold": 62,
          "maxCPUTemperatureThreshold": 80,
          "maxGPUTemperatureThreshold": 80,
          "upperVisionPanelThreshold": 55,
          "cpu_count_sw": 0,
          "gpu_count_sw": 0,
          "panel_count_sw": 0,
          "pressure_low_count_sw": 0,
          "vision_count_sw": 0,
          "motor_ampere_count_sw": 0,
          "cpufreq": "0 (undefined)",
          "gpufreq": "0 (undefined)",
          "panelfreq": "0 (undefined)",
          "visionfreq": "0 (undefined)",
          "pressurefreq": "0 (undefined)",
          "motorfreq": "0 (undefined)"
        }
      },
      {
        "deviceId": "ML_TEAM",
        "data": {
          "cpu_count": 0,
          "gpu_count": 0,
          "panel_count": 0,
          "vision_count": 0,
          "ampere_count": 0,
          "air_pressure_count": 0,
          "device_running": "00:04:38",
          "sorting_running": "00:00:58",
          "cpu_val": "63.00",
          "gpu_val": "52.00",
          "panel_val": "30.00",
          "vision_val": "30.00",
          "ampere_val": "0.00",
          "air_pressure_val": "5.60",
          "cpu_time": "00:00:00",
          "gpu_time": "00:00:00",
          "ampere_time": "00:00:00",
          "air_pressure_time": "00:00:00",
          "panel_time": "00:00:00",
          "vision_time": "00:00:00",
          "motorAmpereThreshold": 6,
          "airPressureLowerValueThreshold": 4.5,
          "upperPanelThreshold": 50,
          "maxCPUTemperatureThreshold": 90,
          "maxGPUTemperatureThreshold": 90,
          "upperVisionPanelThreshold": 55,
          "cpu_count_sw": 0,
          "gpu_count_sw": 0,
          "panel_count_sw": 0,
          "pressure_low_count_sw": 0,
          "vision_count_sw": 0,
          "motor_ampere_count_sw": 0,
          "cpufreq": "0 (63.00)",
          "gpufreq": "0 (52.00)",
          "panelfreq": "0 (30.00)",
          "visionfreq": "0 (30.00)",
          "pressurefreq": "0 (5.60)",
          "motorfreq": "0 (0.00)"
        }
      }
    ]
  },
  {
    "orgName": "Srichakra Polyplast India",
    "data": [
      {
        "deviceId": "SRICHAKRA_SUKA_1_1",
        "data": {
          "cpu_count": 0,
          "gpu_count": 0,
          "panel_count": 0,
          "vision_count": 0,
          "ampere_count": 169464,
          "air_pressure_count": 12370,
          "device_running": "23:40:21",
          "sorting_running": "23:40:21",
          "cpu_val": "91.00",
          "gpu_val": "67.00",
          "panel_val": "0.00",
          "vision_val": "0.00",
          "ampere_val": "10.35",
          "air_pressure_val": "3.24",
          "cpu_time": "00:00:00",
          "gpu_time": "00:00:00",
          "ampere_time": "11:46:06",
          "air_pressure_time": "00:51:32",
          "panel_time": "00:00:00",
          "vision_time": "00:00:00",
          "motorAmpereThreshold": 6,
          "airPressureLowerValueThreshold": 4.5,
          "upperPanelThreshold": 50,
          "maxCPUTemperatureThreshold": 100,
          "maxGPUTemperatureThreshold": 90,
          "upperVisionPanelThreshold": 55,
          "cpu_count_sw": 0,
          "gpu_count_sw": 0,
          "panel_count_sw": 0,
          "pressure_low_count_sw": 7840,
          "vision_count_sw": 0,
          "motor_ampere_count_sw": 0,
          "cpufreq": "0 (91.00)",
          "gpufreq": "0 (67.00)",
          "panelfreq": "0 (0.00)",
          "visionfreq": "0 (0.00)",
          "pressurefreq": "7840 (3.24)",
          "motorfreq": "0 (10.35)"
        }
      },
      {
        "deviceId": "SUKA-AI-V3-1.4-10050",
        "data": {
          "cpu_count": 0,
          "gpu_count": 40,
          "panel_count": 0,
          "vision_count": 0,
          "ampere_count": 8,
          "air_pressure_count": 4,
          "device_running": "23:18:26",
          "sorting_running": "23:04:12",
          "cpu_val": "82.00",
          "gpu_val": "80.00",
          "panel_val": "40.00",
          "vision_val": "36.00",
          "ampere_val": "5.80",
          "air_pressure_val": "4.01",
          "cpu_time": "00:00:00",
          "gpu_time": "00:00:10",
          "ampere_time": "00:00:02",
          "air_pressure_time": "00:00:01",
          "panel_time": "00:00:00",
          "vision_time": "00:00:00",
          "motorAmpereThreshold": 5.5,
          "airPressureLowerValueThreshold": 4.2,
          "upperPanelThreshold": 62,
          "maxCPUTemperatureThreshold": 85,
          "maxGPUTemperatureThreshold": 80,
          "upperVisionPanelThreshold": 55,
          "cpu_count_sw": 0,
          "gpu_count_sw": 2,
          "panel_count_sw": 0,
          "pressure_low_count_sw": 4,
          "vision_count_sw": 0,
          "motor_ampere_count_sw": 0,
          "cpufreq": "0 (82.00)",
          "gpufreq": "2 (80.00)",
          "panelfreq": "0 (40.00)",
          "visionfreq": "0 (36.00)",
          "pressurefreq": "4 (4.01)",
          "motorfreq": "0 (5.80)"
        }
      }
    ]
  },
  {
    "orgName": "Mk Plastics",
    "data": [
      {
        "deviceId": "MKP_SUKA_1",
        "data": {
          "cpu_count": 0,
          "gpu_count": 0,
          "panel_count": 0,
          "vision_count": 0,
          "ampere_count": 12,
          "air_pressure_count": 1,
          "device_running": "12:01:36",
          "sorting_running": "10:24:42",
          "cpu_val": "84.00",
          "gpu_val": "71.00",
          "ampere_val": "7.51",
          "air_pressure_val": "0.00",
          "cpu_time": "00:00:00",
          "gpu_time": "00:00:00",
          "ampere_time": "00:00:03",
          "air_pressure_time": "00:00:00",
          "panel_time": "00:00:00",
          "vision_time": "00:00:00",
          "motorAmpereThreshold": 6,
          "airPressureLowerValueThreshold": 4,
          "upperPanelThreshold": 50,
          "maxCPUTemperatureThreshold": 90,
          "maxGPUTemperatureThreshold": 90,
          "upperVisionPanelThreshold": 55,
          "cpu_count_sw": 0,
          "gpu_count_sw": 0,
          "panel_count_sw": 0,
          "pressure_low_count_sw": 1,
          "vision_count_sw": 0,
          "motor_ampere_count_sw": 0,
          "cpufreq": "0 (84.00)",
          "gpufreq": "0 (71.00)",
          "panelfreq": "0 (undefined)",
          "visionfreq": "0 (undefined)",
          "pressurefreq": "1 (0.00)",
          "motorfreq": "0 (7.51)"
        }
      }
    ]
  },
  {
    "orgName": "Nepra Resource Management",
    "data": [
      {
        "deviceId": "JNAS_1200",
        "data": {
          "cpu_count": 0,
          "gpu_count": 0,
          "panel_count": 0,
          "vision_count": 0,
          "ampere_count": 0,
          "air_pressure_count": 0,
          "device_running": "00:00:00",
          "sorting_running": "00:00:00",
          "cpu_time": "00:00:00",
          "gpu_time": "00:00:00",
          "ampere_time": "00:00:00",
          "air_pressure_time": "00:00:00",
          "panel_time": "00:00:00",
          "vision_time": "00:00:00",
          "motorAmpereThreshold": 0,
          "airPressureLowerValueThreshold": 0,
          "upperPanelThreshold": 0,
          "maxCPUTemperatureThreshold": 0,
          "maxGPUTemperatureThreshold": 0,
          "upperVisionPanelThreshold": 0,
          "cpu_count_sw": 0,
          "gpu_count_sw": 0,
          "panel_count_sw": 0,
          "pressure_low_count_sw": 0,
          "vision_count_sw": 0,
          "motor_ampere_count_sw": 0,
          "cpufreq": "0 (undefined)",
          "gpufreq": "0 (undefined)",
          "panelfreq": "0 (undefined)",
          "visionfreq": "0 (undefined)",
          "pressurefreq": "0 (undefined)",
          "motorfreq": "0 (undefined)"
        }
      },
      {
        "deviceId": "JNAS_1000",
        "data": {
          "cpu_count": 0,
          "gpu_count": 0,
          "panel_count": 0,
          "vision_count": 0,
          "ampere_count": 0,
          "air_pressure_count": 0,
          "device_running": "00:00:00",
          "sorting_running": "00:00:00",
          "cpu_time": "00:00:00",
          "gpu_time": "00:00:00",
          "ampere_time": "00:00:00",
          "air_pressure_time": "00:00:00",
          "panel_time": "00:00:00",
          "vision_time": "00:00:00",
          "motorAmpereThreshold": 0,
          "airPressureLowerValueThreshold": 0,
          "upperPanelThreshold": 0,
          "maxCPUTemperatureThreshold": 0,
          "maxGPUTemperatureThreshold": 0,
          "upperVisionPanelThreshold": 0,
          "cpu_count_sw": 0,
          "gpu_count_sw": 0,
          "panel_count_sw": 0,
          "pressure_low_count_sw": 0,
          "vision_count_sw": 0,
          "motor_ampere_count_sw": 0,
          "cpufreq": "0 (undefined)",
          "gpufreq": "0 (undefined)",
          "panelfreq": "0 (undefined)",
          "visionfreq": "0 (undefined)",
          "pressurefreq": "0 (undefined)",
          "motorfreq": "0 (undefined)"
        }
      },
      {
        "deviceId": "SANTEJ_800",
        "data": {
          "cpu_count": 0,
          "gpu_count": 0,
          "panel_count": 0,
          "vision_count": 0,
          "ampere_count": 0,
          "air_pressure_count": 0,
          "device_running": "00:00:00",
          "sorting_running": "00:00:00",
          "cpu_time": "00:00:00",
          "gpu_time": "00:00:00",
          "ampere_time": "00:00:00",
          "air_pressure_time": "00:00:00",
          "panel_time": "00:00:00",
          "vision_time": "00:00:00",
          "motorAmpereThreshold": 0,
          "airPressureLowerValueThreshold": 0,
          "upperPanelThreshold": 0,
          "maxCPUTemperatureThreshold": 0,
          "maxGPUTemperatureThreshold": 0,
          "upperVisionPanelThreshold": 0,
          "cpu_count_sw": 0,
          "gpu_count_sw": 0,
          "panel_count_sw": 0,
          "pressure_low_count_sw": 0,
          "vision_count_sw": 0,
          "motor_ampere_count_sw": 0,
          "cpufreq": "0 (undefined)",
          "gpufreq": "0 (undefined)",
          "panelfreq": "0 (undefined)",
          "visionfreq": "0 (undefined)",
          "pressurefreq": "0 (undefined)",
          "motorfreq": "0 (undefined)"
        }
      }
    ]
  },
  {
    "orgName": "Rpg",
    "data": [
      {
        "deviceId": "rpg-su20-10038",
        "data": {
          "cpu_count": 0,
          "gpu_count": 0,
          "panel_count": 0,
          "vision_count": 0,
          "ampere_count": 1444,
          "air_pressure_count": 1,
          "device_running": "23:54:11",
          "sorting_running": "02:57:19",
          "cpu_val": "64.00",
          "gpu_val": "66.00",
          "panel_val": "35.00",
          "vision_val": "47.00",
          "ampere_val": "13.32",
          "air_pressure_val": "4.05",
          "cpu_time": "00:00:00",
          "gpu_time": "00:00:00",
          "ampere_time": "00:06:01",
          "air_pressure_time": "00:00:00",
          "panel_time": "00:00:00",
          "vision_time": "00:00:00",
          "motorAmpereThreshold": 6.699999999999999,
          "airPressureLowerValueThreshold": 4.5,
          "upperPanelThreshold": 62,
          "maxCPUTemperatureThreshold": 80,
          "maxGPUTemperatureThreshold": 80,
          "upperVisionPanelThreshold": 62,
          "cpu_count_sw": 0,
          "gpu_count_sw": 0,
          "panel_count_sw": 0,
          "pressure_low_count_sw": 1,
          "vision_count_sw": 0,
          "motor_ampere_count_sw": 0,
          "cpufreq": "0 (64.00)",
          "gpufreq": "0 (66.00)",
          "panelfreq": "0 (35.00)",
          "visionfreq": "0 (47.00)",
          "pressurefreq": "1 (4.05)",
          "motorfreq": "0 (13.32)"
        }
      },
      {
        "deviceId": "RPG-SU20-10047",
        "data": {
          "cpu_count": 0,
          "gpu_count": 0,
          "panel_count": 0,
          "vision_count": 0,
          "ampere_count": 0,
          "air_pressure_count": 9,
          "device_running": "23:49:36",
          "sorting_running": "02:43:27",
          "cpu_val": "68.00",
          "gpu_val": "68.00",
          "panel_val": "37.00",
          "vision_val": "40.00",
          "ampere_val": "6.12",
          "air_pressure_val": "4.36",
          "cpu_time": "00:00:00",
          "gpu_time": "00:00:00",
          "ampere_time": "00:00:00",
          "air_pressure_time": "00:00:02",
          "panel_time": "00:00:00",
          "vision_time": "00:00:00",
          "motorAmpereThreshold": 7.099999999999999,
          "airPressureLowerValueThreshold": 4.5,
          "upperPanelThreshold": 62,
          "maxCPUTemperatureThreshold": 80,
          "maxGPUTemperatureThreshold": 80,
          "upperVisionPanelThreshold": 55,
          "cpu_count_sw": 0,
          "gpu_count_sw": 0,
          "panel_count_sw": 0,
          "pressure_low_count_sw": 8,
          "vision_count_sw": 0,
          "motor_ampere_count_sw": 0,
          "cpufreq": "0 (68.00)",
          "gpufreq": "0 (68.00)",
          "panelfreq": "0 (37.00)",
          "visionfreq": "0 (40.00)",
          "pressurefreq": "8 (4.36)",
          "motorfreq": "0 (6.12)"
        }
      }
    ]
  },
  {
    "orgName": "Sulochana Cotton Mills Pvt Ltd",
    "data": [
      {
        "deviceId": "SCM-SU14-10039",
        "data": {
          "cpu_count": 41,
          "gpu_count": 0,
          "panel_count": 0,
          "vision_count": 0,
          "ampere_count": 0,
          "air_pressure_count": 25824,
          "device_running": "19:05:48",
          "sorting_running": "16:06:26",
          "cpu_val": "85.00",
          "gpu_val": "69.00",
          "panel_val": "37.00",
          "vision_val": "37.00",
          "ampere_val": "4.97",
          "air_pressure_val": "0.03",
          "cpu_time": "00:00:10",
          "gpu_time": "00:00:00",
          "ampere_time": "00:00:00",
          "air_pressure_time": "01:47:36",
          "panel_time": "00:00:00",
          "vision_time": "00:00:00",
          "motorAmpereThreshold": 5.200000000000003,
          "airPressureLowerValueThreshold": 4.2,
          "upperPanelThreshold": 62,
          "maxCPUTemperatureThreshold": 85,
          "maxGPUTemperatureThreshold": 80,
          "upperVisionPanelThreshold": 60,
          "cpu_count_sw": 0,
          "gpu_count_sw": 0,
          "panel_count_sw": 0,
          "pressure_low_count_sw": 0,
          "vision_count_sw": 0,
          "motor_ampere_count_sw": 0,
          "cpufreq": "0 (85.00)",
          "gpufreq": "0 (69.00)",
          "panelfreq": "0 (37.00)",
          "visionfreq": "0 (37.00)",
          "pressurefreq": "0 (0.03)",
          "motorfreq": "0 (4.97)"
        }
      }
    ]
  },
  {
    "orgName": "Alliance",
    "data": [
      {
        "deviceId": "SUK-AL-V3-2.0-10045",
        "data": {
          "cpu_count": 0,
          "gpu_count": 0,
          "panel_count": 0,
          "vision_count": 0,
          "ampere_count": 0,
          "air_pressure_count": 0,
          "device_running": "23:38:23",
          "sorting_running": "21:09:42",
          "cpu_val": "85.00",
          "gpu_val": "78.00",
          "panel_val": "48.00",
          "vision_val": "42.00",
          "ampere_val": "7.47",
          "air_pressure_val": "4.57",
          "cpu_time": "00:00:00",
          "gpu_time": "00:00:00",
          "ampere_time": "00:00:00",
          "air_pressure_time": "00:00:00",
          "panel_time": "00:00:00",
          "vision_time": "00:00:00",
          "motorAmpereThreshold": 7.500000000000001,
          "airPressureLowerValueThreshold": 4,
          "upperPanelThreshold": 62,
          "maxCPUTemperatureThreshold": 87,
          "maxGPUTemperatureThreshold": 80,
          "upperVisionPanelThreshold": 60,
          "cpu_count_sw": 0,
          "gpu_count_sw": 0,
          "panel_count_sw": 0,
          "pressure_low_count_sw": 0,
          "vision_count_sw": 0,
          "motor_ampere_count_sw": 0,
          "cpufreq": "0 (85.00)",
          "gpufreq": "0 (78.00)",
          "panelfreq": "0 (48.00)",
          "visionfreq": "0 (42.00)",
          "pressurefreq": "0 (4.57)",
          "motorfreq": "0 (7.47)"
        }
      },
      {
        "deviceId": "SUK-AL-V3-2.0-10042",
        "data": {
          "cpu_count": 0,
          "gpu_count": 1992,
          "panel_count": 0,
          "vision_count": 0,
          "ampere_count": 8,
          "air_pressure_count": 0,
          "device_running": "23:37:51",
          "sorting_running": "21:01:35",
          "cpu_val": "86.00",
          "gpu_val": "81.00",
          "panel_val": "50.00",
          "vision_val": "42.00",
          "ampere_val": "9.06",
          "air_pressure_val": "4.71",
          "cpu_time": "00:00:00",
          "gpu_time": "00:08:18",
          "ampere_time": "00:00:02",
          "air_pressure_time": "00:00:00",
          "panel_time": "00:00:00",
          "vision_time": "00:00:00",
          "motorAmpereThreshold": 7.500000000000002,
          "airPressureLowerValueThreshold": 4,
          "upperPanelThreshold": 62,
          "maxCPUTemperatureThreshold": 87,
          "maxGPUTemperatureThreshold": 80,
          "upperVisionPanelThreshold": 60,
          "cpu_count_sw": 0,
          "gpu_count_sw": 16,
          "panel_count_sw": 0,
          "pressure_low_count_sw": 0,
          "vision_count_sw": 0,
          "motor_ampere_count_sw": 0,
          "cpufreq": "0 (86.00)",
          "gpufreq": "16 (81.00)",
          "panelfreq": "0 (50.00)",
          "visionfreq": "0 (42.00)",
          "pressurefreq": "0 (4.71)",
          "motorfreq": "0 (9.06)"
        }
      },
      {
        "deviceId": "SUK-AL-V3-2.0-10043",
        "data": {
          "cpu_count": 8,
          "gpu_count": 0,
          "panel_count": 0,
          "vision_count": 0,
          "ampere_count": 55,
          "air_pressure_count": 1,
          "device_running": "23:37:51",
          "sorting_running": "20:57:23",
          "cpu_val": "87.00",
          "gpu_val": "78.00",
          "panel_val": "50.00",
          "vision_val": "45.00",
          "ampere_val": "12.10",
          "air_pressure_val": "3.83",
          "cpu_time": "00:00:02",
          "gpu_time": "00:00:00",
          "ampere_time": "00:00:13",
          "air_pressure_time": "00:00:00",
          "panel_time": "00:00:00",
          "vision_time": "00:00:00",
          "motorAmpereThreshold": 7.100000000000001,
          "airPressureLowerValueThreshold": 4,
          "upperPanelThreshold": 62,
          "maxCPUTemperatureThreshold": 87,
          "maxGPUTemperatureThreshold": 80,
          "upperVisionPanelThreshold": 62,
          "cpu_count_sw": 0,
          "gpu_count_sw": 0,
          "panel_count_sw": 0,
          "pressure_low_count_sw": 1,
          "vision_count_sw": 0,
          "motor_ampere_count_sw": 3,
          "cpufreq": "0 (87.00)",
          "gpufreq": "0 (78.00)",
          "panelfreq": "0 (50.00)",
          "visionfreq": "0 (45.00)",
          "pressurefreq": "1 (3.83)",
          "motorfreq": "3 (12.10)"
        }
      },
      {
        "deviceId": "SUK-AL-V3-2.0-10044",
        "data": {
          "cpu_count": 0,
          "gpu_count": 0,
          "panel_count": 0,
          "vision_count": 0,
          "ampere_count": 14,
          "air_pressure_count": 0,
          "device_running": "23:38:21",
          "sorting_running": "20:15:35",
          "cpu_val": "72.00",
          "gpu_val": "77.00",
          "panel_val": "49.00",
          "vision_val": "42.00",
          "ampere_val": "9.99",
          "air_pressure_val": "4.98",
          "cpu_time": "00:00:00",
          "gpu_time": "00:00:00",
          "ampere_time": "00:00:03",
          "air_pressure_time": "00:00:00",
          "panel_time": "00:00:00",
          "vision_time": "00:00:00",
          "motorAmpereThreshold": 7.500000000000002,
          "airPressureLowerValueThreshold": 4,
          "upperPanelThreshold": 60,
          "maxCPUTemperatureThreshold": 87,
          "maxGPUTemperatureThreshold": 80,
          "upperVisionPanelThreshold": 62,
          "cpu_count_sw": 0,
          "gpu_count_sw": 0,
          "panel_count_sw": 0,
          "pressure_low_count_sw": 0,
          "vision_count_sw": 0,
          "motor_ampere_count_sw": 0,
          "cpufreq": "0 (72.00)",
          "gpufreq": "0 (77.00)",
          "panelfreq": "0 (49.00)",
          "visionfreq": "0 (42.00)",
          "pressurefreq": "0 (4.98)",
          "motorfreq": "0 (9.99)"
        }
      },
      {
        "deviceId": "SUK-AL-V3-1.4-10046",
        "data": {
          "cpu_count": 73,
          "gpu_count": 0,
          "panel_count": 0,
          "vision_count": 0,
          "ampere_count": 10,
          "air_pressure_count": 0,
          "device_running": "23:40:13",
          "sorting_running": "21:08:52",
          "cpu_val": "87.00",
          "gpu_val": "76.00",
          "panel_val": "49.00",
          "vision_val": "42.00",
          "ampere_val": "8.32",
          "air_pressure_val": "4.58",
          "cpu_time": "00:00:18",
          "gpu_time": "00:00:00",
          "ampere_time": "00:00:02",
          "air_pressure_time": "00:00:00",
          "panel_time": "00:00:00",
          "vision_time": "00:00:00",
          "motorAmpereThreshold": 6.6999999999999975,
          "airPressureLowerValueThreshold": 4,
          "upperPanelThreshold": 62,
          "maxCPUTemperatureThreshold": 87,
          "maxGPUTemperatureThreshold": 80,
          "upperVisionPanelThreshold": 60,
          "cpu_count_sw": 0,
          "gpu_count_sw": 0,
          "panel_count_sw": 0,
          "pressure_low_count_sw": 0,
          "vision_count_sw": 0,
          "motor_ampere_count_sw": 4,
          "cpufreq": "0 (87.00)",
          "gpufreq": "0 (76.00)",
          "panelfreq": "0 (49.00)",
          "visionfreq": "0 (42.00)",
          "pressurefreq": "0 (4.58)",
          "motorfreq": "4 (8.32)"
        }
      }
    ]
  },
  {
    "orgName": "Banyan Nation",
    "data": [
      {
        "deviceId": "SUKA-AI-V3-2.0-10049",
        "data": {
          "cpu_count": 0,
          "gpu_count": 0,
          "panel_count": 0,
          "vision_count": 0,
          "ampere_count": 7,
          "air_pressure_count": 21,
          "device_running": "23:49:39",
          "sorting_running": "18:47:09",
          "cpu_val": "84.00",
          "gpu_val": "66.00",
          "panel_val": "40.00",
          "vision_val": "36.00",
          "ampere_val": "7.96",
          "air_pressure_val": "3.56",
          "cpu_time": "00:00:00",
          "gpu_time": "00:00:00",
          "ampere_time": "00:00:01",
          "air_pressure_time": "00:00:05",
          "panel_time": "00:00:00",
          "vision_time": "00:00:00",
          "motorAmpereThreshold": 7.499999999999998,
          "airPressureLowerValueThreshold": 4,
          "upperPanelThreshold": 62,
          "maxCPUTemperatureThreshold": 95,
          "maxGPUTemperatureThreshold": 80,
          "upperVisionPanelThreshold": 55,
          "cpu_count_sw": 0,
          "gpu_count_sw": 0,
          "panel_count_sw": 0,
          "pressure_low_count_sw": 21,
          "vision_count_sw": 0,
          "motor_ampere_count_sw": 0,
          "cpufreq": "0 (84.00)",
          "gpufreq": "0 (66.00)",
          "panelfreq": "0 (40.00)",
          "visionfreq": "0 (36.00)",
          "pressurefreq": "21 (3.56)",
          "motorfreq": "0 (7.96)"
        }
      }
    ]
  },
  {
    "orgName": "Vindhya Ceramics",
    "data": [
      {
        "deviceId": "SUK-AL-V3-2.0-10053",
        "data": {
          "cpu_count": 0,
          "gpu_count": 0,
          "panel_count": 0,
          "vision_count": 0,
          "ampere_count": 2,
          "air_pressure_count": 378,
          "device_running": "22:08:18",
          "sorting_running": "21:42:37",
          "cpu_val": "87.00",
          "gpu_val": "75.00",
          "panel_val": "42.00",
          "vision_val": "41.00",
          "ampere_val": "7.25",
          "air_pressure_val": "2.23",
          "cpu_time": "00:00:00",
          "gpu_time": "00:00:00",
          "ampere_time": "00:00:00",
          "air_pressure_time": "00:01:34",
          "panel_time": "00:00:00",
          "vision_time": "00:00:00",
          "motorAmpereThreshold": 7.199999999999998,
          "airPressureLowerValueThreshold": 4,
          "upperPanelThreshold": 62,
          "maxCPUTemperatureThreshold": 96,
          "maxGPUTemperatureThreshold": 80,
          "upperVisionPanelThreshold": 62,
          "cpu_count_sw": 0,
          "gpu_count_sw": 0,
          "panel_count_sw": 0,
          "pressure_low_count_sw": 168,
          "vision_count_sw": 0,
          "motor_ampere_count_sw": 0,
          "cpufreq": "0 (87.00)",
          "gpufreq": "0 (75.00)",
          "panelfreq": "0 (42.00)",
          "visionfreq": "0 (41.00)",
          "pressurefreq": "168 (2.23)",
          "motorfreq": "0 (7.25)"
        }
      },
      {
        "deviceId": "SUK-AL-V3-2.0-10052",
        "data": {
          "cpu_count": 0,
          "gpu_count": 0,
          "panel_count": 0,
          "vision_count": 0,
          "ampere_count": 8,
          "air_pressure_count": 0,
          "device_running": "23:42:09",
          "sorting_running": "22:15:33",
          "cpu_val": "90.00",
          "gpu_val": "72.00",
          "panel_val": "44.00",
          "vision_val": "38.00",
          "ampere_val": "6.48",
          "air_pressure_val": "4.35",
          "cpu_time": "00:00:00",
          "gpu_time": "00:00:00",
          "ampere_time": "00:00:02",
          "air_pressure_time": "00:00:00",
          "panel_time": "00:00:00",
          "vision_time": "00:00:00",
          "motorAmpereThreshold": 6.199999999999996,
          "airPressureLowerValueThreshold": 4,
          "upperPanelThreshold": 62,
          "maxCPUTemperatureThreshold": 96,
          "maxGPUTemperatureThreshold": 80,
          "upperVisionPanelThreshold": 60,
          "cpu_count_sw": 0,
          "gpu_count_sw": 0,
          "panel_count_sw": 0,
          "pressure_low_count_sw": 0,
          "vision_count_sw": 0,
          "motor_ampere_count_sw": 0,
          "cpufreq": "0 (90.00)",
          "gpufreq": "0 (72.00)",
          "panelfreq": "0 (44.00)",
          "visionfreq": "0 (38.00)",
          "pressurefreq": "0 (4.35)",
          "motorfreq": "0 (6.48)"
        }
      },
      {
        "deviceId": "SUK-AL-V3-1.4-10054",
        "data": {
          "cpu_count": 0,
          "gpu_count": 0,
          "panel_count": 0,
          "vision_count": 0,
          "ampere_count": 826,
          "air_pressure_count": 142,
          "device_running": "23:41:48",
          "sorting_running": "22:03:41",
          "cpu_val": "78.00",
          "gpu_val": "74.00",
          "panel_val": "48.00",
          "vision_val": "37.00",
          "ampere_val": "8.84",
          "air_pressure_val": "1.71",
          "cpu_time": "00:00:00",
          "gpu_time": "00:00:00",
          "ampere_time": "00:03:26",
          "air_pressure_time": "00:00:35",
          "panel_time": "00:00:00",
          "vision_time": "00:00:00",
          "motorAmpereThreshold": 6,
          "airPressureLowerValueThreshold": 4,
          "upperPanelThreshold": 62,
          "maxCPUTemperatureThreshold": 96,
          "maxGPUTemperatureThreshold": 80,
          "upperVisionPanelThreshold": 60,
          "cpu_count_sw": 0,
          "gpu_count_sw": 0,
          "panel_count_sw": 0,
          "pressure_low_count_sw": 12,
          "vision_count_sw": 0,
          "motor_ampere_count_sw": 0,
          "cpufreq": "0 (78.00)",
          "gpufreq": "0 (74.00)",
          "panelfreq": "0 (48.00)",
          "visionfreq": "0 (37.00)",
          "pressurefreq": "12 (1.71)",
          "motorfreq": "0 (8.84)"
        }
      }
    ]
  },
  {
    "orgName": "Shree Ram Raghav",
    "data": [
      {
        "deviceId": "SUK-AL-V3-2.0-10055",
        "data": {
          "cpu_count": 63,
          "gpu_count": 0,
          "panel_count": 0,
          "vision_count": 0,
          "ampere_count": 5,
          "air_pressure_count": 0,
          "device_running": "22:15:03",
          "sorting_running": "12:29:01",
          "cpu_val": "100.00",
          "gpu_val": "75.00",
          "panel_val": "43.00",
          "vision_val": "41.00",
          "ampere_val": "8.91",
          "air_pressure_val": "4.02",
          "cpu_time": "00:00:15",
          "gpu_time": "00:00:00",
          "ampere_time": "00:00:01",
          "air_pressure_time": "00:00:00",
          "panel_time": "00:00:00",
          "vision_time": "00:00:00",
          "motorAmpereThreshold": 6.9999999999999964,
          "airPressureLowerValueThreshold": 4,
          "upperPanelThreshold": 62,
          "maxCPUTemperatureThreshold": 95,
          "maxGPUTemperatureThreshold": 80,
          "upperVisionPanelThreshold": 60,
          "cpu_count_sw": 25,
          "gpu_count_sw": 0,
          "panel_count_sw": 0,
          "pressure_low_count_sw": 0,
          "vision_count_sw": 0,
          "motor_ampere_count_sw": 0,
          "cpufreq": "25 (100.00)",
          "gpufreq": "0 (75.00)",
          "panelfreq": "0 (43.00)",
          "visionfreq": "0 (41.00)",
          "pressurefreq": "0 (4.02)",
          "motorfreq": "0 (8.91)"
        }
      },
      {
        "deviceId": "SUK-AL-V3-1.4-10057",
        "data": {
          "cpu_count": 0,
          "gpu_count": 0,
          "panel_count": 0,
          "vision_count": 0,
          "ampere_count": 353,
          "air_pressure_count": 0,
          "device_running": "23:47:39",
          "sorting_running": "11:17:27",
          "cpu_val": "78.00",
          "gpu_val": "69.00",
          "panel_val": "40.00",
          "vision_val": "35.00",
          "ampere_val": "10.49",
          "air_pressure_val": "4.72",
          "cpu_time": "00:00:00",
          "gpu_time": "00:00:00",
          "ampere_time": "00:01:28",
          "air_pressure_time": "00:00:00",
          "panel_time": "00:00:00",
          "vision_time": "00:00:00",
          "motorAmpereThreshold": 7.0000000000000036,
          "airPressureLowerValueThreshold": 4.5,
          "upperPanelThreshold": 62,
          "maxCPUTemperatureThreshold": 95,
          "maxGPUTemperatureThreshold": 80,
          "upperVisionPanelThreshold": 60,
          "cpu_count_sw": 0,
          "gpu_count_sw": 0,
          "panel_count_sw": 0,
          "pressure_low_count_sw": 0,
          "vision_count_sw": 0,
          "motor_ampere_count_sw": 1,
          "cpufreq": "0 (78.00)",
          "gpufreq": "0 (69.00)",
          "panelfreq": "0 (40.00)",
          "visionfreq": "0 (35.00)",
          "pressurefreq": "0 (4.72)",
          "motorfreq": "1 (10.49)"
        }
      },
      {
        "deviceId": "SUK-AL-V3-2.0-10056",
        "data": {
          "cpu_count": 0,
          "gpu_count": 0,
          "panel_count": 0,
          "vision_count": 0,
          "ampere_count": 0,
          "air_pressure_count": 0,
          "device_running": "22:23:53",
          "sorting_running": "12:47:23",
          "cpu_val": "88.00",
          "gpu_val": "76.00",
          "panel_val": "46.00",
          "vision_val": "39.00",
          "ampere_val": "7.10",
          "air_pressure_val": "4.12",
          "cpu_time": "00:00:00",
          "gpu_time": "00:00:00",
          "ampere_time": "00:00:00",
          "air_pressure_time": "00:00:00",
          "panel_time": "00:00:00",
          "vision_time": "00:00:00",
          "motorAmpereThreshold": 7.5,
          "airPressureLowerValueThreshold": 4,
          "upperPanelThreshold": 62,
          "maxCPUTemperatureThreshold": 95,
          "maxGPUTemperatureThreshold": 80,
          "upperVisionPanelThreshold": 60,
          "cpu_count_sw": 0,
          "gpu_count_sw": 0,
          "panel_count_sw": 0,
          "pressure_low_count_sw": 0,
          "vision_count_sw": 0,
          "motor_ampere_count_sw": 0,
          "cpufreq": "0 (88.00)",
          "gpufreq": "0 (76.00)",
          "panelfreq": "0 (46.00)",
          "visionfreq": "0 (39.00)",
          "pressurefreq": "0 (4.12)",
          "motorfreq": "0 (7.10)"
        }
      }
    ]
  },
  {
    "orgName": "Re Sustainability Ltd",
    "data": [
      {
        "deviceId": "SUK-AI-V3-1.4-10070",
        "data": {
          "cpu_count": 0,
          "gpu_count": 0,
          "panel_count": 0,
          "vision_count": 0,
          "ampere_count": 0,
          "air_pressure_count": 0,
          "device_running": "00:00:00",
          "sorting_running": "00:00:00",
          "cpu_time": "00:00:00",
          "gpu_time": "00:00:00",
          "ampere_time": "00:00:00",
          "air_pressure_time": "00:00:00",
          "panel_time": "00:00:00",
          "vision_time": "00:00:00",
          "motorAmpereThreshold": 7.500000000000002,
          "airPressureLowerValueThreshold": 4.5,
          "upperPanelThreshold": 60,
          "maxCPUTemperatureThreshold": 85,
          "maxGPUTemperatureThreshold": 75,
          "upperVisionPanelThreshold": 55,
          "cpu_count_sw": 0,
          "gpu_count_sw": 0,
          "panel_count_sw": 0,
          "pressure_low_count_sw": 0,
          "vision_count_sw": 0,
          "motor_ampere_count_sw": 0,
          "cpufreq": "0 (undefined)",
          "gpufreq": "0 (undefined)",
          "panelfreq": "0 (undefined)",
          "visionfreq": "0 (undefined)",
          "pressurefreq": "0 (undefined)",
          "motorfreq": "0 (undefined)"
        }
      }
    ]
  },
  {
    "orgName": "Starlite",
    "data": [
      {
        "deviceId": "SUK-AI-V3-2.0-10060",
        "data": {
          "cpu_count": 0,
          "gpu_count": 0,
          "panel_count": 0,
          "vision_count": 0,
          "ampere_count": 13,
          "air_pressure_count": 31860,
          "device_running": "08:24:16",
          "sorting_running": "05:31:17",
          "cpu_val": "82.00",
          "gpu_val": "66.00",
          "panel_val": "44.00",
          "vision_val": "42.00",
          "ampere_val": "8.80",
          "air_pressure_val": "0.03",
          "cpu_time": "00:00:00",
          "gpu_time": "00:00:00",
          "ampere_time": "00:00:03",
          "air_pressure_time": "02:12:45",
          "panel_time": "00:00:00",
          "vision_time": "00:00:00",
          "motorAmpereThreshold": 7.5,
          "airPressureLowerValueThreshold": 4,
          "upperPanelThreshold": 60,
          "maxCPUTemperatureThreshold": 90,
          "maxGPUTemperatureThreshold": 80,
          "upperVisionPanelThreshold": 60,
          "cpu_count_sw": 0,
          "gpu_count_sw": 0,
          "panel_count_sw": 0,
          "pressure_low_count_sw": 8,
          "vision_count_sw": 0,
          "motor_ampere_count_sw": 0,
          "cpufreq": "0 (82.00)",
          "gpufreq": "0 (66.00)",
          "panelfreq": "0 (44.00)",
          "visionfreq": "0 (42.00)",
          "pressurefreq": "8 (0.03)",
          "motorfreq": "0 (8.80)"
        }
      }
    ]
  },
  {
    "orgName": "Jaipuria Bevearges & Food Industries Pvt Ltd",
    "data": [
      {
        "deviceId": "SUK-AI-V3-2.0-10063",
        "data": {
          "cpu_count": 0,
          "gpu_count": 0,
          "panel_count": 0,
          "vision_count": 0,
          "ampere_count": 0,
          "air_pressure_count": 0,
          "device_running": "00:00:00",
          "sorting_running": "00:00:00",
          "cpu_time": "00:00:00",
          "gpu_time": "00:00:00",
          "ampere_time": "00:00:00",
          "air_pressure_time": "00:00:00",
          "panel_time": "00:00:00",
          "vision_time": "00:00:00",
          "motorAmpereThreshold": 7.5,
          "airPressureLowerValueThreshold": 4.5,
          "upperPanelThreshold": 60,
          "maxCPUTemperatureThreshold": 85,
          "maxGPUTemperatureThreshold": 75,
          "upperVisionPanelThreshold": 55,
          "cpu_count_sw": 0,
          "gpu_count_sw": 0,
          "panel_count_sw": 0,
          "pressure_low_count_sw": 0,
          "vision_count_sw": 0,
          "motor_ampere_count_sw": 0,
          "cpufreq": "0 (undefined)",
          "gpufreq": "0 (undefined)",
          "panelfreq": "0 (undefined)",
          "visionfreq": "0 (undefined)",
          "pressurefreq": "0 (undefined)",
          "motorfreq": "0 (undefined)"
        }
      },
      {
        "deviceId": "SUK-AI-V3-2.0-10062",
        "data": {
          "cpu_count": 0,
          "gpu_count": 0,
          "panel_count": 0,
          "vision_count": 0,
          "ampere_count": 0,
          "air_pressure_count": 0,
          "device_running": "00:00:00",
          "sorting_running": "00:00:00",
          "cpu_time": "00:00:00",
          "gpu_time": "00:00:00",
          "ampere_time": "00:00:00",
          "air_pressure_time": "00:00:00",
          "panel_time": "00:00:00",
          "vision_time": "00:00:00",
          "motorAmpereThreshold": 7.499999999999995,
          "airPressureLowerValueThreshold": 4.5,
          "upperPanelThreshold": 55,
          "maxCPUTemperatureThreshold": 85,
          "maxGPUTemperatureThreshold": 75,
          "upperVisionPanelThreshold": 60,
          "cpu_count_sw": 0,
          "gpu_count_sw": 0,
          "panel_count_sw": 0,
          "pressure_low_count_sw": 0,
          "vision_count_sw": 0,
          "motor_ampere_count_sw": 0,
          "cpufreq": "0 (undefined)",
          "gpufreq": "0 (undefined)",
          "panelfreq": "0 (undefined)",
          "visionfreq": "0 (undefined)",
          "pressurefreq": "0 (undefined)",
          "motorfreq": "0 (undefined)"
        }
      },
      {
        "deviceId": "SUK-AI-V3-1.4-10064",
        "data": {
          "cpu_count": 0,
          "gpu_count": 0,
          "panel_count": 0,
          "vision_count": 0,
          "ampere_count": 0,
          "air_pressure_count": 0,
          "device_running": "00:00:00",
          "sorting_running": "00:00:00",
          "cpu_time": "00:00:00",
          "gpu_time": "00:00:00",
          "ampere_time": "00:00:00",
          "air_pressure_time": "00:00:00",
          "panel_time": "00:00:00",
          "vision_time": "00:00:00",
          "motorAmpereThreshold": 7.499999999999995,
          "airPressureLowerValueThreshold": 4.5,
          "upperPanelThreshold": 62,
          "maxCPUTemperatureThreshold": 85,
          "maxGPUTemperatureThreshold": 80,
          "upperVisionPanelThreshold": 60,
          "cpu_count_sw": 0,
          "gpu_count_sw": 0,
          "panel_count_sw": 0,
          "pressure_low_count_sw": 0,
          "vision_count_sw": 0,
          "motor_ampere_count_sw": 0,
          "cpufreq": "0 (undefined)",
          "gpufreq": "0 (undefined)",
          "panelfreq": "0 (undefined)",
          "visionfreq": "0 (undefined)",
          "pressurefreq": "0 (undefined)",
          "motorfreq": "0 (undefined)"
        }
      }
    ]
  },
  {
    "orgName": "Project Uday",
    "data": [
      {
        "deviceId": "SAN-AI-V1-1.0-10033",
        "data": {
          "cpu_count": 27581,
          "gpu_count": 0,
          "panel_count": 10,
          "vision_count": 10,
          "ampere_count": 141,
          "air_pressure_count": 252551,
          "device_running": "23:23:14",
          "sorting_running": "03:25:35",
          "cpu_val": "88.00",
          "gpu_val": "76.00",
          "panel_val": "236.00",
          "vision_val": "236.00",
          "ampere_val": "15.25",
          "air_pressure_val": "0.04",
          "cpu_time": "01:54:55",
          "gpu_time": "00:00:00",
          "ampere_time": "00:00:35",
          "air_pressure_time": "17:32:17",
          "panel_time": "00:00:02",
          "vision_time": "00:00:02",
          "motorAmpereThreshold": 7.5,
          "airPressureLowerValueThreshold": 4.2,
          "upperPanelThreshold": 62,
          "maxCPUTemperatureThreshold": 80,
          "maxGPUTemperatureThreshold": 80,
          "upperVisionPanelThreshold": 55,
          "cpu_count_sw": 0,
          "gpu_count_sw": 0,
          "panel_count_sw": 28,
          "pressure_low_count_sw": 0,
          "vision_count_sw": 0,
          "motor_ampere_count_sw": 3,
          "cpufreq": "0 (88.00)",
          "gpufreq": "0 (76.00)",
          "panelfreq": "28 (236.00)",
          "visionfreq": "0 (236.00)",
          "pressurefreq": "0 (0.04)",
          "motorfreq": "3 (15.25)"
        }
      }
    ]
  },
  {
    "orgName": "Poddar",
    "data": [
      {
        "deviceId": "SUK-AI-V3-1.4-10061",
        "data": {
          "cpu_count": 0,
          "gpu_count": 0,
          "panel_count": 0,
          "vision_count": 0,
          "ampere_count": 0,
          "air_pressure_count": 0,
          "device_running": "00:00:00",
          "sorting_running": "00:00:00",
          "cpu_time": "00:00:00",
          "gpu_time": "00:00:00",
          "ampere_time": "00:00:00",
          "air_pressure_time": "00:00:00",
          "panel_time": "00:00:00",
          "vision_time": "00:00:00",
          "motorAmpereThreshold": 6,
          "airPressureLowerValueThreshold": 4,
          "upperPanelThreshold": 62,
          "maxCPUTemperatureThreshold": 60,
          "maxGPUTemperatureThreshold": 80,
          "upperVisionPanelThreshold": 60,
          "cpu_count_sw": 0,
          "gpu_count_sw": 0,
          "panel_count_sw": 0,
          "pressure_low_count_sw": 0,
          "vision_count_sw": 0,
          "motor_ampere_count_sw": 0,
          "cpufreq": "0 (undefined)",
          "gpufreq": "0 (undefined)",
          "panelfreq": "0 (undefined)",
          "visionfreq": "0 (undefined)",
          "pressurefreq": "0 (undefined)",
          "motorfreq": "0 (undefined)"
        }
      }
    ]
  },
  {
    "orgName": "Meta",
    "data": [
      {
        "deviceId": "SUK-AI-V3-2.0-10075",
        "data": {
          "cpu_count": 0,
          "gpu_count": 0,
          "panel_count": 2,
          "vision_count": 2,
          "ampere_count": 10265,
          "air_pressure_count": 1406,
          "device_running": "01:16:09",
          "sorting_running": "00:00:00",
          "cpu_val": "89.00",
          "gpu_val": "62.00",
          "panel_val": "236.00",
          "vision_val": "236.00",
          "ampere_val": "50.00",
          "air_pressure_val": "0.00",
          "cpu_time": "00:00:00",
          "gpu_time": "00:00:00",
          "ampere_time": "00:42:46",
          "air_pressure_time": "00:05:51",
          "panel_time": "00:00:00",
          "vision_time": "00:00:00",
          "motorAmpereThreshold": 7.500000000000002,
          "airPressureLowerValueThreshold": 4,
          "upperPanelThreshold": 62,
          "maxCPUTemperatureThreshold": 100,
          "maxGPUTemperatureThreshold": 80,
          "upperVisionPanelThreshold": 60,
          "cpu_count_sw": 0,
          "gpu_count_sw": 0,
          "panel_count_sw": 2,
          "pressure_low_count_sw": 0,
          "vision_count_sw": 0,
          "motor_ampere_count_sw": 6,
          "cpufreq": "0 (89.00)",
          "gpufreq": "0 (62.00)",
          "panelfreq": "2 (236.00)",
          "visionfreq": "0 (236.00)",
          "pressurefreq": "0 (0.00)",
          "motorfreq": "6 (50.00)"
        }
      },
      {
        "deviceId": "SUK-AI-V3-2.0-10076",
        "data": {
          "cpu_count": 2,
          "gpu_count": 0,
          "panel_count": 0,
          "vision_count": 0,
          "ampere_count": 0,
          "air_pressure_count": 222736,
          "device_running": "15:28:04",
          "sorting_running": "10:42:47",
          "cpu_val": "100.00",
          "gpu_val": "74.00",
          "panel_val": "46.00",
          "vision_val": "50.00",
          "ampere_val": "7.30",
          "air_pressure_val": "0.00",
          "cpu_time": "00:00:00",
          "gpu_time": "00:00:00",
          "ampere_time": "00:00:00",
          "air_pressure_time": "15:28:04",
          "panel_time": "00:00:00",
          "vision_time": "00:00:00",
          "motorAmpereThreshold": 7.500000000000002,
          "airPressureLowerValueThreshold": 4,
          "upperPanelThreshold": 62,
          "maxCPUTemperatureThreshold": 99,
          "maxGPUTemperatureThreshold": 80,
          "upperVisionPanelThreshold": 60,
          "cpu_count_sw": 0,
          "gpu_count_sw": 0,
          "panel_count_sw": 22,
          "pressure_low_count_sw": 0,
          "vision_count_sw": 4,
          "motor_ampere_count_sw": 0,
          "cpufreq": "0 (100.00)",
          "gpufreq": "0 (74.00)",
          "panelfreq": "22 (46.00)",
          "visionfreq": "4 (50.00)",
          "pressurefreq": "0 (0.00)",
          "motorfreq": "0 (7.30)"
        }
      }
    ]
  }
]